openmeterio/openmeter

.github/workflows/ci.yaml
=> ci: add fossa scan

README.md
Link examples in readme to increase visibility.
=> docs(readme): link examples to readme

quickstart/README.md
Update the API response for the meter values.
=> docs: update quickstart API response

.envrc, .github/workflows/ci.yaml, .gitignore, .goreleaser.yaml, Makefile, README.md, flake.lock, flake.nix
- Update developer environment
- Add precommit hooks
=> chore: update devenv

examples/export-stripe-node/.gitignore, examples/export-stripe-node/.prettierrc.json, examples/export-stripe-node/README.md, examples/export-stripe-node/app.ts, examples/export-stripe-node/openapi.d.ts, examples/export-stripe-node/package-lock.json, examples/export-stripe-node/package.json, examples/export-stripe-node/setup.ts, examples/export-stripe-node/tsconfig.json, examples/ingest-openai-node/app.ts, examples/ingest-openai-node/package-lock.json
Adding Stripe node example with periodic reporting.
=> feat(example): add stripe node

examples/export-stripe-go/report.go
PR https://github.com/openmeterio/openmeter/pull/8 changes value type.
=> fix(examples): value type for go stripe example

docker-compose.yaml
Upgrade to latest 7.4.0 Confluent distribution.
=> chore(docker-compose): update to latest confluent images

README.md
=> docs(readme): add demo video

api/api.gen.go, api/openapi.yml, examples/export-stripe-node/openapi.d.ts, examples/ingest-openai-node/openapi.d.ts, quickstart/README.md
Rename v1 to v1alpha1 in API.
It clearly communicates that the API may still change and in fact allows us to rollout breaking changes in a less painful way.
=> Rename v1 to v1alpha1

docs/event-ingestion.md
=> docs(event-ingestion): add

config.go, main.go
Improve configuration structure
=> chore: improve configuration

internal/streaming/kafka_connector/query_test.go, internal/streaming/kafka_connector/sql/values.tpl.sql
=> fix(ksqldb): values query

.github/workflows/artifacts.yaml, .github/workflows/ci.yaml, Dockerfile, quickstart/docker-compose.ci.yaml, quickstart/ingest.sh, quickstart/verify.sh
Simple e2e test based on quickstart.
=> ci: add quickstart test

README.md
Add nix installation instructions
=> docs: add nix installation instructions

api/clients/node/README.md, api/clients/node/index.ts, api/clients/node/package-lock.json, api/clients/node/package.json, api/clients/node/scripts/postgenerate.ts, api/clients/node/test/api.test.ts, api/clients/node/tsconfig.json, api/clients/node/vitest.config.ts
Add Node.js SDK: `@openmeter/sdk`.
(Fixes #64)
=> feat(clients): add Node.js client generation

.github/workflows/pr-checks.yaml, README.md
- Center align logo
- Include links to client SDKs.
=> docs: add client SDKs to README

examples/export-stripe-node/package.json, examples/ingest-fastify-node/.gitignore, examples/ingest-fastify-node/.prettierrc.json, examples/ingest-fastify-node/README.md, examples/ingest-fastify-node/app.ts, examples/ingest-fastify-node/package-lock.json, examples/ingest-fastify-node/package.json, examples/ingest-fastify-node/tsconfig.json, examples/ingest-openai-node/package.json
=> feat(examples): add fastify

examples/ingest-fastify-node/README.md, examples/ingest-fastify-node/app.ts, examples/ingest-fastify-node/package-lock.json, examples/ingest-fastify-node/package.json
List metered usage on root API.
=> feat(example): list meters in fastify example

README.md
=> docs(readme): add quickstart demo video

config.go, deploy/charts/openmeter/templates/configmap.yaml, main.go, quickstart/config.yaml
Support Kafka, KSQL, and Schema Registry authentications.
**Breaking change:**
- `ingest.kafka.schemaRegistry` => `schemaRegistry.url`
=> feat(config): add auth support

internal/ingest/kafkaingest/schema.go, main.go
Remove topic specific prefix from schema. We can reuse the same schema between different prefixes
Related #102
=> feat!: remove topic prefix from schema

examples/ingest-openai-node/app.ts, examples/ingest-openai-node/package-lock.json, examples/ingest-openai-node/package.json
Add query example to OpenAI example.
=> feat(example): add query example to openai

docker-compose.yaml, internal/ingest/kafkaingest/kafkaingest.go, internal/streaming/kafka_connector/connector.go, internal/streaming/kafka_connector/query.go, internal/streaming/kafka_connector/query_test.go, internal/streaming/kafka_connector/sql/detected_events_table.tpl.sql, internal/streaming/kafka_connector/sql/events_stream.tpl.sql, main.go
Move ingest kafka topic creation from ksqldb
Related #102
=> Kafka topic creation

config.go, internal/ingest/httpingest/httpingest.go, internal/ingest/httpingest/httpingest_test.go, internal/ingest/kafkaingest/namespace.go, internal/namespace/namespace.go, internal/namespace/namespace_test.go, internal/server/router/router.go, internal/server/server_test.go, internal/streaming/clickhouse_connector/connector.go, internal/streaming/ksqldb_connector/meter_test.go, internal/streaming/ksqldb_connector/namespace.go, internal/streaming/ksqldb_connector/query_test.go, main.go
- Configurable default namespace
- Configurable namespace management
=> feat(namespace): configure default and management

internal/streaming/clickhouse_connector/connector.go
Strengthen connect topics regex by reusing OpenAPI regex.
=> feat(sink): strengthen connect topics regex

config.go, main.go
Since v6 Redis supports username.
=> feat(dedupe): support redis username

internal/streaming/clickhouse_connector/query_test.go, internal/streaming/clickhouse_connector/sql/query_meter_view.tpl.sql
=> feat(processor): order clickhouse query response

internal/streaming/clickhouse_connector/query.go, internal/streaming/clickhouse_connector/query_test.go
Fix ClickHouse querying. With args client does type conversion.
=> fix(processor): clickhouse query from and to

internal/server/router/router.go, internal/streaming/clickhouse_connector/connector.go
Debug log query execution time
=> feat(route): debug log query execution time

internal/streaming/clickhouse_connector/query.go, internal/streaming/clickhouse_connector/query_test.go
Fix date filters with ClickHouse. ClickHouse expects seconds.
=> fix(processor): date filters with clickhouse

config.go, main.go
Refactor log config
Move some initialization code to config
Clean up `main` a little
=> Refactor log config

examples/ingest-logs/README.md, examples/ingest-logs/docker-compose.yaml, examples/ingest-logs/vector.yaml
Add a log parsing igest example with Vector.
Depends on: https://github.com/openmeterio/openmeter/pull/96 as Vector sends array of events.
=> feat(examples): add ingest-logs

config.go, go.mod, go.sum, main.go
Refactor deduplication config to avoid invalid scenarios (eg. both redis and memory are enabled).
Polymorphic configuration is easier to understand:
```yaml
dedupe:
enabled: true
driver: redis|memory
config:
address: ...
size: ...
```
**This is a breaking change! A new release will require configuration updates as well**
=> Refactor dedupe configuration

.github/workflows/artifacts.yaml, .github/workflows/ci.yaml
Add image build for next branch
=> ci: add next build

config.go
Fix missing decode hook to parse redis expiration config.
=> fix: redis expiration config parser

.github/workflows/ci.yaml, docker-compose.yaml, quickstart/config.clickhouse.yaml, quickstart/config.ksqldb.yaml, quickstart/docker-compose.yaml
run quickstart tests for ClickHouse
=> ci: run quickstart tests for ClickHouse

config.go, main.go, pkg/kafka/kafka.go, pkg/kafka/log.go
Kafka outputs logs to stderr by default.
This PR makes it send logs to our standard logger.
=> feat(kafka): send log messages to the standard logger

.github/workflows/ci.yaml, flake.nix
=> Run pre-commit hooks in CI

.github/workflows/artifacts.yaml, .github/workflows/ci.yaml
=> ci: remove next from build targets

config.go, go.mod, go.sum
=> feat: instrument redis

ci/magefile.go, config.go, flake.lock, flake.nix, go.mod, go.sum, internal/ingest/httpingest/httpingest.go, internal/ingest/kafkaingest/collector.go, internal/ingest/kafkaingest/namespace.go, internal/server/logger.go, internal/server/router/router.go, internal/server/server.go, internal/sink/kafka_connect.go, internal/streaming/clickhouse_connector/connector.go, internal/streaming/ksqldb_connector/connector.go, internal/streaming/ksqldb_connector/meter.go, main.go, pkg/gosundheit/logger.go, pkg/kafka/log.go
=> Upgrade Go to 1.21

internal/ingest/dedupe.go, internal/ingest/dedupe_test.go, internal/ingest/httpingest/httpingest.go, internal/ingest/httpingest/httpingest_test.go, internal/ingest/ingest.go, internal/ingest/inmemory.go, internal/ingest/inmemory_test.go, internal/ingest/kafkaingest/collector.go
Propagate context in ingest collector
This is required for tracing
=> feat: propagate context in ingest collector

config.go, main.go
=> refactor: move log configuration under telemetry

config/config.go, config/config_test.go, config/dedupe.go, config/ingest.go, config/namespace.go, config/processor.go, config/schema.go, config/sink.go, config/telemetry.go, config/testdata/complete.yaml, config/viper.go, main.go
=> Relocate config

.github/workflows/artifacts.yaml, Dockerfile
Make sure the proper version is added to the binary inside the container.
Currently it always reports "unknown".
=> build: fix version propagation into the container

.air.toml, config/processor.go
To match `docker-compose.yaml` settings.
=> fix(config): clickhouse defaults

config/sink.go
Continuation of: https://github.com/openmeterio/openmeter/pull/216
=> fix(config): sink clickhouse defaults

.github/workflows/ci.yaml
=> ci: add nix cache

api/api.gen.go, api/client/go/client.gen.go, api/openapi.yaml, internal/server/router/router.go, internal/streaming/clickhouse_connector/connector.go, pkg/models/meter.go
=> feat: add new meter query endpoint to openapi spec

api/api.gen.go, api/client/go/client.gen.go, api/openapi.yaml, docker-compose.yaml, etc/kafka-connect/Dockerfile, internal/server/router/router.go, internal/server/server_test.go, internal/streaming/clickhouse_connector/connector.go, internal/streaming/clickhouse_connector/query.go, internal/streaming/connector.go
=> New list meter subjects endpoint

Makefile, docs/seeder.md, etc/seed/seed.yaml, flake.nix
=> Add seeder

config/config_test.go, config/processor.go, config/testdata/complete.yaml, main.go
remove unnecessary enabled flag from clickhouse
=> refactor: remove unnecessary enabled flag from clickhouse

api/client/node/README.md, api/client/node/clients/meter.ts, api/client/node/package-lock.json, api/client/node/package.json, api/client/node/schemas/openapi.ts, api/client/node/test/agent.ts, api/client/node/test/api.test.ts
- Cut release thats not behind npm beta flag
- Add `meter.query` support
- Add `meter.subjects` support
=> feat(api): node client beta6

config/config_test.go, config/dedupe.go, config/sink.go, config/testdata/complete.yaml, internal/sink/kafka_connect.go, main.go, quickstart/config.yaml
Fixes #230
There is one major downside to this PR: we lose connector defaults, but I believe it's something we can live with.
I will improve the dev configuration in a subsequent PR.
=> Kafka connect refactor

config/config.go, config/dedupe.go, config/ingest.go, config/namespace.go, config/processor.go
Expose configuration options for external usage.
=> feat: expose configuration

internal/server/router/router.go, internal/server/server_test.go, internal/streaming/clickhouse_connector/connector.go, internal/streaming/connector.go
Refactor the query interface and return a single result struct from the streaming connector.
This will make future integrations slightly easier.
=> refactor: return a single query result struct

config.example.yaml
Add kafka connect config to dev example
=> chore: update example config

.gitmodules, deploy/README.md, deploy/charts/openmeter/Chart.lock, deploy/charts/openmeter/Chart.yaml, deploy/charts/openmeter/templates/clickhouse.yaml, deploy/charts/openmeter/templates/configmap.yaml, deploy/charts/openmeter/templates/deployment.yaml, deploy/charts/openmeter/templates/kafka.yaml, deploy/charts/openmeter/values.yaml
Update helm chart to use ClickHouse and latest image.
TODO:
=> chore(deploy): update helm chart

docs/decisions/0005-clickhouse.md
Add decision doc about adopting ClickHouse.
=> docs(decisions): adopting clickhouse

api/client/node/README.md, api/client/node/clients/event.ts, api/client/node/clients/meter.ts, api/client/node/schemas/openapi.ts, api/client/node/test/agent.ts, api/client/node/test/api.test.ts, api/client/node/test/mocks.ts
Make raw events query API available in Node SDK.
=> feat(api): add events query to node

api/client/node/README.md, api/client/node/index.ts, api/client/node/next.ts, api/client/node/package-lock.json, api/client/node/package.json, api/client/node/schemas/openapi.ts, api/client/node/test/next.test.ts
I'm still debating if this should be in SDK or just an example.
I can see an argument for both. What do you think?
=> feat(api): add vercel ai helper to node sdk

flake.lock, flake.nix
Upgrade flake and dev dependencies
=> chore: upgrade flake

openmeter/dedupe/dedupe.go, openmeter/dedupe/memorydedupe/memorydedupe.go, openmeter/dedupe/redisdedupe/redisdedupe.go, openmeter/ingest/dedupe.go, openmeter/ingest/httpingest/httpingest.go, openmeter/ingest/ingest.go, openmeter/ingest/inmemory.go, openmeter/ingest/kafkaingest/collector.go, openmeter/ingest/kafkaingest/namespace.go, openmeter/ingest/kafkaingest/serializer/json.go, openmeter/ingest/kafkaingest/serializer/serializer.go, openmeter/meter/inmemory.go, openmeter/meter/meter.go, openmeter/namespace/namespace.go, openmeter/openmeter.go, openmeter/server/router/router.go, openmeter/server/server.go, openmeter/streaming/clickhouse_connector/connector.go, openmeter/streaming/clickhouse_connector/model.go, openmeter/streaming/connector.go
Allow importing OpenMeter as a library.
This is just the initial export. More refactoring will follow.
**⚠️ The API exported in this PR is not considered stable.**
=> Export OpenMeter as a library

docker-compose.yaml, etc/kafka-connect/Dockerfile
Update Kafka Connect and the Clickhouse Connector
=> chore: update kafka connect

docs/event-ingestion.md
Just improve the wording in the `event-ingestion.md` file a bit.
=> Minor wording change in event-ingestion.md

cmd/sink-worker/main.go, internal/dedupe/redisdedupe/redisdedupe.go
- fix sink dedupe config
- set keys at once via lua scripting
=> feat(dedupe): set multiple keys once

go.mod, go.sum, internal/sink/sink.go
Improve handling when neither offset commit nor redis sink succeeds in sink worker.
=> feat(sink): with retry

.github/workflows/generate-client-node.yaml
Generate Node.js client automatically when the OpenAPI schema changes.
=> ci(api): add Node.js client generation workflow

.github/workflows/generate-client-python.yaml
See:
- https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
- https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
=> ci(api): use bot to open PR

docs/decisions/0001-event-streaming-platform.md, docs/decisions/0003-idempotency.md, docs/decisions/0004-partitioning.md, docs/event-ingestion.md, docs/seeder.md
Typo fixes in markdown files under the docs/ directory
=> Fix typos in docs/

flake.lock, flake.nix
=> build: use official dagger flake

.spectral.yaml, Makefile, api/openapi.yaml, ci/dagger.json, ci/main.go
Add a linter to make sure we catch openapi errors
Usage: `dagger call lint openapi`
=> Lint openapi

examples/export-stripe-go/README.md, examples/export-stripe-node/README.md, examples/ingest-fastify-node/README.md, examples/ingest-kubernetes-pod-time-go/README.md, examples/ingest-openai-node/README.md
This is a PR to fix the typos inside the files under the examples/ directory
=> Fixed typos in examples/

api/api.gen.go, api/client/go/client.gen.go, api/client/node/README.md, api/client/node/clients/portal.ts, api/client/node/index.ts, api/client/node/schemas/openapi.ts, api/client/node/test/agent.ts, api/client/node/test/api.test.ts, api/openapi.yaml, internal/server/router/portal.go, internal/server/server_test.go
Add portal endpoints as unimplemented.
=> feat(api): add portal

api/client/go/README.md, api/client/go/client.go
Add a sugar method for ingest.
Improve readme.
=> feat(client): improve go api

.github/workflows/generate-client-node.yaml, .github/workflows/publish-client-node.yaml, .github/workflows/publish-python-client.yaml, api/client/node/package.json, api/client/python/pyproject.toml
Publish Node.js client to npm and Python client to PyPI.
NOTE: If there were API changes, wait for client update PRs to be merged first.
=> Automatically publish clients on new tag

internal/streaming/clickhouse_connector/connector.go
=> fix(connector): pass sql args to list events

internal/streaming/clickhouse_connector/query.go, internal/streaming/clickhouse_connector/query_test.go
=> fix(streaming): namespace shadow

api/api.gen.go, api/client/go/client.gen.go, api/openapi.yaml, internal/server/router/event.go, internal/server/router/router.go, internal/server/server_test.go, internal/sink/model.go, internal/sink/namespaces.go, internal/sink/namespaces_test.go, internal/sink/sink.go, internal/sink/storage.go, internal/sink/storage_test.go, internal/streaming/clickhouse_connector/connector.go, internal/streaming/clickhouse_connector/query.go, internal/streaming/clickhouse_connector/query_test.go, internal/streaming/connector.go
- `GET /api/v1/events` return format to include validation error
- Adding  `validation_error` column to `om_events`
If you `MUST` migrate follow:
As pre-1.0.0 release, this breaking change requires manual migration.
**1. Stop sink-worker or Kafka Connect**
This stop ingestion to the ClickHouse DB. Events will queue up in Kafka topic so that you won't lose new data just delay meter aggregates.
**2. Update Events Table in ClickHouse**
Run the following command to update your ClickHouse DB:
```sh
curl -u default:default -d "ALTER TABLE openmeter.om_events ADD COLUMN validation_error String AFTER namespace" -X POST http://localhost:8123
```
**3. Start OpenMeter With Recreate Config**
Add the following to your `config.yaml` temporary.
```yaml
aggregation:
createOrReplaceMeter: true …
```
=> feat(event)!: store validation error in raw events table

api/openapi.yaml, internal/server/router/router.go, internal/server/server_test.go
=> fix(route): validate query group by

internal/streaming/clickhouse_connector/connector.go, internal/streaming/clickhouse_connector/query.go, internal/streaming/clickhouse_connector/query_test.go, internal/streaming/query_params.go
=> feat(connector): filter by group by

docker-compose.yaml, etc/wiretap/config.docker.yaml
=> chore: add wiretap to dev tools

Makefile, ci/dagger.json, ci/go.mod, ci/main.go, flake.lock
=> chore: update flake

.github/workflows/ci.yaml, ci/build.go, ci/dagger.json, ci/main.go, ci/utils.go
Try to improve build times by using Dagger.
=> ci: update CI modules

.github/workflows/release.yaml
=> ci: fix dagger secret

api/api.gen.go, api/client/go/client.gen.go, api/openapi.yaml, internal/server/router/subject.go, internal/server/server_test.go
=> feat(api): add subjects

.github/workflows/ci.yaml, .github/workflows/release.yaml, flake.lock
=> Upgrade Dagger

api/api.gen.go, api/client/go/client.gen.go, api/client/node/clients/event.ts, api/client/node/clients/portal.ts, api/client/node/clients/subject.ts, api/client/node/index.ts, api/client/node/schemas/openapi.ts, api/client/node/test/agent.ts, api/client/node/test/api.test.ts, api/client/node/test/mocks.ts, api/openapi.yaml, internal/server/router/subject.go, internal/server/server_test.go
- add subject get and delete
- add subject to Node SDK
- fix event list return type in Node SDK
=> feat(api): add subject get and delete

internal/streaming/clickhouse_connector/query.go, internal/streaming/clickhouse_connector/query_test.go
Fix SQL for query events implementation
=> fix(clickhouse): fix query events implementation

benthos-collector.Dockerfile, collector/benthos/presets/http-server/input.yaml, collector/benthos/presets/http-server/output.yaml, collector/benthos/presets/kubernetes-pod-exec-time/config.yaml, deploy/charts/benthos-collector/templates/_helpers.tpl
Add presets to benthos collector.
=> feat: add benthos collector presets

cmd/benthos-collector/main.go, collector/benthos/input/kubernetes.go, collector/benthos/input/schedule.go, collector/benthos/output/openmeter.go, go.mod, go.sum
Moving Benthos plugins to this repo for now (until we figure out how to distribute API clients and libraries based on them)
=> feat(collector/benthos): move plugins to this repo for now

.github/workflows/release.yaml, flake.nix, justfile
=> chore: add release script

.github/workflows/artifacts.yaml, ci/build.go, ci/release.go
ci: fix benthos collector dockerfile
=> ci: fix benthos collector dockerfile

internal/sink/sink.go
We currently let sink workers continue processing new messages after offset commit errors.
Make error fatal.
Also, remove unnecessary `StoreMessage.` (we handle offsets manually)
=> feat(sink): treat commit offset fatal

internal/sink/offset.go, internal/sink/offset_test.go, internal/sink/sink.go
Ensure we only commit partitions that are still assigned to consumers.
=> feat(sink): ensure we only commit for assigned partitions

ci/main.go, flake.lock, flake.nix, go.mod
=> feat: update go to 1.22

flake.lock
=> feat: update flake

cmd/server/main.go, go.mod, go.sum, internal/ingest/httpingest/httpingest.go, internal/ingest/httpingest/httpingest_test.go, internal/server/authenticator/authenticator.go, internal/server/router/event.go, internal/server/router/meter.go, internal/server/router/meter_query.go, internal/server/router/meter_subject.go, internal/server/router/portal.go, internal/server/router/router.go, internal/server/router/subject.go, internal/server/server.go, internal/server/server_test.go, pkg/contextx/attr.go, pkg/contextx/log.go, pkg/errorsx/handler.go, pkg/models/problem.go
Add better error handling
4xx error logging is removed: we can enable access logs for that
Error handler logs 5xx error (when necessary)
It's going to become significantly easier, once we move away from HTTP handlers for core logic (most error mapping can happen outside of controllers)
=> Add better error handling

.golangci.yaml, collector/benthos/input/otel_log.go, collector/benthos/internal/LICENSE, collector/benthos/internal/message/batch.go, collector/benthos/internal/message/transaction.go, collector/benthos/internal/shutdown/signaler.go, collector/benthos/output/otel_log.go, examples/collectors/README.md, examples/collectors/otel-log/.env.dist, examples/collectors/otel-log/README.md, examples/collectors/otel-log/config.yaml, examples/collectors/otel-log/docker-compose.yaml, examples/collectors/otel-log/seed/config.yaml, go.mod
OTEL log ingestion plugin for Benthos using the OTLP gRPC log exporter API.
=> Add OTEL log ingestion

internal/ingest/httpingest/httpingest.go, internal/ingest/httpingest/httpingest_test.go
This PR fixes the returned status code (from 500 to 400) when an invalid event is ingested.
=> fix: status code returned by ingest on invalid event

benthos-collector.Dockerfile, deploy/charts/benthos-collector/templates/_helpers.tpl, deploy/charts/benthos-collector/templates/deployment.yaml, examples/collectors/database/docker-compose.common.yaml, examples/collectors/http-server/docker-compose.yaml
=> Fix benthos collector

.github/workflows/ci.yaml, .github/workflows/release.yaml
Dependabot PRs fail due to using smaller instances for CI.
This PR clears some disk space.
=> ci: free up some space on GHA

quickstart/docker-compose.yaml
=> fix(quickstart): docker compose extends

examples/collectors/otel-log/docker-compose.yaml
Fix benthos command in otel example
=> fix(examples/otel): docker compose command

ci/build.go
=> ci: bump dagger cache

.golangci.yaml
=> ci: increase lint timeout

api/client/web/README.md
=> chore: update broken link to nextjs example

.github/workflows/generate-client-python.yaml
Docker login to access `ghcr.io/openmeterio/autorest-python:latest`
=> fix(ci): access python generator image

api/client/python/Makefile
=> chore(api): update python client makefile

.github/workflows/release.yaml
=> fix: ci release

cmd/server/main.go, internal/ingest/ingestdriver/http_transport.go, internal/ingest/ingestdriver/http_transport_test.go, internal/ingest/service.go, internal/server/router/event.go, internal/server/router/router.go, internal/server/server_test.go, openmeter/ingest/ingestdriver/http_transport.go, openmeter/ingest/service.go, pkg/errorsx/handler.go, pkg/framework/README.md, pkg/framework/internal/operation/name.go, pkg/framework/operation/log.go, pkg/framework/operation/middleware.go, pkg/framework/operation/middleware_test.go, pkg/framework/operation/name.go, pkg/framework/operation/name_test.go, pkg/framework/operation/operation.go, pkg/framework/operation/operation_test.go, pkg/framework/transport/http/handler.go, pkg/framework/transport/http/options.go, pkg/framework/transport/httptransport/handler.go, pkg/framework/transport/httptransport/options.go
Currently most of the business logic resides in HTTP handlers which requires us to write a lot of boilerplate code for error handling, authorization, etc.
This PR introduces a new framework to make moving common logic into middleware easier.
=> refactor: new framework

.github/dependabot.yaml
Update dependabot to include client SDKs.
=> chore(github): update dependabot

internal/server/router/meter_query.go, internal/streaming/clickhouse_connector/connector.go
Set window sizes for total usage query in connector.
=> refactor(query): move window size setter to connector

.github/dependabot.yaml
=> chore: remove unnecessary labels

.github/workflows/ci.yaml
=> chore: upgrade dagger in GHA

e2e/e2e_test.go
Implement a call that checks if the events are processed in a specific amount of time instead of static waits.
It speeds up integration tests and checks whether the prerequisites for the next test cases have been fulfilled, helping with troubleshooting (e.g., it clearly shows if we have an issue with event processing or ledger).
Before:
`┃ ok      github.com/openmeterio/openmeter/e2e    40.696s`
After
`┃ ok      github.com/openmeterio/openmeter/e2e    21.688s`
=> test(e2e): no wait

.github/dependabot.yaml
=> chore: tweak dependabot config

ci/build.go, ci/lint.go, ci/main.go, ci/release.go, dagger.json
=> ci: improve helm publish

.github/workflows/ci.yaml
=> ci: consolidate dagger usage

ci/release.go
fix: python package publishing
=> fix: python package publishing

.github/workflows/generate-client-node.yaml, .github/workflows/generate-client-web.yaml, .github/workflows/release.yaml, ci/generate.go, ci/main.go, ci/release.go
Generate node and web sdk with Dagger
Requires #846
=> Generate node and web sdk with Dagger

ci/release.go
=> ci: fix node release

ci/go.mod, ci/release.go
=> Fix node release

go.mod, go.sum
Bump `github.com/confluentinc/confluent-kafka-go/v2` to the latest `v2.4.0` (relesed yesterday)
=> chore(deps): bump confluent-kafka-go to 2.4.0

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/sdk-node.yaml, .github/workflows/sdk-python.yaml, .github/workflows/sdk-web.yaml, ci/build.go, dagger.json, flake.lock
=> chore: update dagger

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/sdk-node.yaml, .github/workflows/sdk-python.yaml, .github/workflows/sdk-web.yaml
=> ci: update dagger

.golangci.yaml
=> Tune golangci lint

.github/dependabot.yaml
=> ci: tune dependency updates

openmeter/ingest/kafkaingest/collector.go
Export kafka ingest NewCollector
=> feat(openmeter): export new kafka collector

internal/sink/sink.go
=> refactor(sink-worker): use main context on flush

cmd/sink-worker/main.go, config/config_test.go, config/ingest.go, config/sink.go, internal/sink/sink.go
Reverting the following changes as it might be related to a bug we have been still investigating:
* #910 
* #906 
* #903 
* #880 
* #856
=> revert: sink worker changes

.github/workflows/ci.yaml
Free disk space due to warnings
Fixes #(issue)
=> ci: free disk space before e2e

benthos-collector.Dockerfile, ci/main.go, go.mod
=> ci: update go version

.github/workflows/ci.yaml
Export engine logs for debugging purposes.
=> ci: add engine log export

.github/workflows/ci.yaml
=> ci: fix engine log export

internal/sink/sink.go
Log Kafka client local errors in `sink.Sink` on *warning* level as most of these errors are informational and the client is able to handle/recover from them automatically.
=> refactor: log Kafka local errors on warn level

internal/sink/model.go, internal/sink/namespaces.go, internal/sink/namespaces_test.go, internal/sink/sink.go, internal/sink/storage.go, internal/sink/storage_test.go
Refactor event parsing and validation in `sink-worker`.
=> refactor(sink-worker): event parsing and validation

collector/benthos/input/otel_log.go
Fix copy-paste in benthos plugin
=> chore: fix copy paste

e2e/e2e_test.go
=> Fix panic in e2e tests

internal/sink/namespaces.go, internal/sink/namespaces_test.go, internal/sink/sink.go, openmeter/sink/sink.go
Fixes #OM-660
This patch ensures that the full batch that has been successfully created in the clickhouse store is available via a callback for further processing.
=> feat: add callbacks support for ingested batches

Makefile
Command to run SDK generation code. Rational is its faster to run it locally than wait for the client generation PRs.
Fixes #(issue)
=> chore: add command to gen sdks

api/api.gen.go, api/client/go/client.gen.go, api/client/node/schemas/openapi.ts, api/client/web/src/client/openapi.ts, api/openapi.yaml, api/types/entitlement.go, e2e/e2e_test.go, internal/credit/recurrence.go, internal/entitlement/connector.go, internal/entitlement/entitlement.go, internal/entitlement/httpdriver/entitlement.go, internal/entitlement/httpdriver/parser.go, internal/entitlement/metered/balance_test.go, internal/entitlement/metered/grant_owner_adapter.go, internal/entitlement/postgresadapter/entitlement.go, internal/entitlement/repository.go, internal/entitlement/static/connector.go, internal/productcatalog/feature_connector.go, internal/productcatalog/httpdriver/feature.go, internal/productcatalog/postgresadapter/feature.go, internal/productcatalog/postgresadapter/feature_test.go, internal/server/router/entitlement.go
- introduces UsagePeriod and IsSoftLimit fields and stores them
- fixes API type parsing on entitlement creation
Fixes #(issue)
=> Storing Usage Period

internal/entitlement/httpdriver/entitlement.go, internal/entitlement/httpdriver/errors.go, internal/entitlement/httpdriver/metered.go
- unify error handling for entitlements
Fixes #(issue)
=> Unify error handling for entitlements

openmeter/entitlement/metered/types.go
Export type alias for `MeteredEntitlementValue`.
=> feat: add type alias for MeteredEntitlementValue

internal/entitlement/connector.go, internal/entitlement/postgresadapter/entitlement.go, openmeter/entitlement/types.go
Add `SubjectKey` to `entitlement.ListEntitlementsParams` to allow filtering entitlements based on _subject_.
=> feat: add subjectKey to entitlement list params

internal/entitlement/connector.go, internal/entitlement/postgresadapter/entitlement.go
Add `FeatureIDs` to `entitlement.ListEntitlementsParams` to allow filtering _entitlements_ based on _features_ they are belong to.
=> feat(api): allow filtering entitlements by feature IDs

internal/entitlement/postgresadapter/entitlement.go
Fix query used for filtering _entitlements_ by _feature ids_.
=> fix(api): query used for filtering entitlements

internal/entitlement/metered/grant_owner_adapter.go
We should be able to fetch and query and use entitlements of archived features.
Fixes #(issue)
=> fix: fetch query params of archived features

internal/productcatalog/httpdriver/errors.go, internal/productcatalog/httpdriver/feature.go
Add error encoding for errors returned by feature API.
=> feat: add encoding errors for feature API

openmeter/entitlement/metered/types.go
was missing from the public api
=> feat: expose entitlement response object

.envrc
=> chore(direnv): upgrade to 3.0.5

api/api.gen.go, api/client/go/client.gen.go, api/client/node/clients/feature.ts, api/client/node/package-lock.json, api/openapi.yaml, internal/productcatalog/feature.go
- Removed `deletedAt` from required fields
- Add description about `deletedAt` and `updatedAt` defaults
=> fix(api): feature times

api/client/node/README.md, api/client/node/clients/client.ts, api/client/node/clients/entitlement.ts, api/client/node/clients/feature.ts, api/client/node/clients/grant.ts, api/client/node/clients/subject.ts, api/client/node/index.ts, api/client/node/schemas/openapi.ts, api/client/node/test/agent.ts, api/client/node/test/api.test.ts, api/client/node/test/mocks.ts
- Feature Node API
- Grant Node API
- Subject Entitlement Node API
=> feat(api): add feature and entitlement to node api

internal/credit/grant_connector.go, internal/entitlement/boolean/connector.go, internal/entitlement/connector.go, internal/entitlement/entitlement_types.go, internal/entitlement/metered/connector.go, internal/entitlement/metered/grant_owner_adapter.go, internal/entitlement/static/connector.go, pkg/framework/entutils/transaction.go
Ensures that entitlement creation happens as a single atomic operation
Fixes #(issue)
We'll have to refactor later to a more generic pattern
=> feat: include entitlement creation in a single transaction

internal/entitlement/metered/entitlement_grant.go, internal/entitlement/postgresadapter/entitlement.go
=> Validate entitlement exists for grant create and deletion

internal/entitlement/httpdriver/parser.go
=> Return isSoftLimit on EntitlementMetered API

internal/credit/grant_connector.go
Grants issued take effect at start of current window, not at end
=> feat: grants take effect at start of current window, not at end

e2e/entitlement/regression/scenario_test.go, internal/credit/balance_connector.go, internal/credit/grant.go, internal/entitlement/metered/balance_test.go
=> fix: check if grants expire at reset time

e2e/e2e_test.go, internal/entitlement/boolean/connector.go, internal/entitlement/connector.go, internal/entitlement/entitlement.go, internal/entitlement/entitlement_test.go, internal/entitlement/entitlement_types.go, internal/entitlement/metered/balance_test.go, internal/entitlement/metered/connector.go, internal/entitlement/metered/grant_owner_adapter.go, internal/entitlement/static/connector.go
- Fixing some inaccuracies regarding the initial CurrentUsagePeriod calculations
- Properly sharing the transaction in which entitlement creation runs
Fixes #(issue)
=> Correct Usage Period Calculations

e2e/entitlement/regression/scenario_test.go, internal/credit/balance_connector.go, internal/credit/grant.go, internal/credit/grant_connector.go, internal/credit/postgresadapter/balance_snapshot.go, internal/entitlement/boolean/connector.go, internal/entitlement/connector.go, internal/entitlement/httpdriver/entitlement.go, internal/entitlement/httpdriver/metered.go, internal/entitlement/metered/balance.go, internal/entitlement/metered/balance_test.go, internal/entitlement/metered/connector.go, internal/entitlement/metered/entitlement_grant.go, internal/entitlement/postgresadapter/entitlement.go, internal/entitlement/static/connector.go, internal/productcatalog/postgresadapter/feature.go, pkg/clock/clock.go, pkg/clock/clock_test.go, pkg/framework/entutils/mixins.go, test/entitlement/regression/framework_test.go, test/entitlement/regression/scenario_test.go
This patch adds the clock package that we can use to model complex scenarios over time. The first regression test illustrates the usage.
This patch also fixes the underlying issue:
- if a grant expires same time as the reset
=> feat: fix issues when grant expires the same time when a reset happens

internal/entitlement/static/connector.go
=> fix(entitlement): pass config to static create

internal/entitlement/metered/balance.go
Due to an oversight in the calculation logic, all metered usage were calculated towards entitlements. This patch ensures that we only use the specified subject's data.
=> fix: subject filtering for value endpoint

internal/server/router/router.go
- fix router namespace adapter namespace
- validate router config
=> fix(router): namespace driver default

internal/credit/httpdriver/grant.go, internal/entitlement/httpdriver/errors.go, internal/ingest/ingestdriver/http_transport.go, internal/productcatalog/httpdriver/errors.go, pkg/framework/transport/httptransport/handler.go
This feature allows us to act on the actual request, e.g. tracing, falling back to other system locations.
=> feat: add support request in error encorder

internal/debug/httpdriver/metrics.go, openmeter/debug/adapters.go, openmeter/debug/httpdriver/handlers.go, openmeter/debug/httpdriver/types.go, openmeter/debug/types.go
Continuation of https://github.com/openmeterio/openmeter/pull/1135
=> feat(debug): exports

cmd/server/main.go, internal/credit/balance_connector.go, internal/credit/balancesnapshot_connector.go, internal/credit/grant_connector.go, internal/credit/postgresadapter/balance_snapshot.go, internal/credit/postgresadapter/transaction.go, internal/entitlement/metered/balance_test.go, internal/entitlement/metered/reset_test.go, internal/entitlement/metered/utils_test.go, openmeter/credit/adapters.go, openmeter/credit/postgresadapter/adapters.go, openmeter/credit/types.go, test/entitlement/regression/framework_test.go, test/entitlement/regression/scenario_test.go
- Restructure the test files in the entitlement package so they're easier to navigate
- Add missing cleanup & connection closing of test DBs
- Make variable names consistent with interface names
Fixes #(issue)
=> Break up entitlement tests

api/client/node/schemas/openapi.ts, api/client/python/src/openmeter/_operations/_operations.py, api/client/python/src/openmeter/aio/_operations/_operations.py, api/client/web/src/client/openapi.ts
regen API clients
Fixes #(issue)
=> chore: regen api

internal/entitlement/connector.go, internal/entitlement/httpdriver/entitlement.go, internal/entitlement/postgresadapter/entitlement.go
Allow to list entitlements across multiple namespaces using internal connector API.
=> feat: allow to list entitlements across namespaces

Makefile, internal/entitlement/metered/grant_owner_adapter.go, internal/productcatalog/feature.go, internal/productcatalog/feature_connector.go, internal/productcatalog/httpdriver/feature.go, internal/productcatalog/postgresadapter/feature.go, pkg/convert/ptr.go
Removes unnecessary pointer from map property and defines custom type for filtering the meter on a feature.
- Branched from this PR to exclude functionality change https://github.com/openmeterio/openmeter/pull/1144
=> Refactor meter filtering on features

config/config_test.go, config/dedupe.go, pkg/redis/client.go, pkg/redis/config.go
Add a dedicated Redis client package in order to improve reusability of commonly used components.
=> feat: add dedicated redis client package

internal/entitlement/httpdriver/entitlement.go, internal/entitlement/httpdriver/parser.go, openmeter/entitlement/httpdriver/handlers.go
This allows us to reuse the value to api parsing logic in the Cloud without code duplication.
=> feat: allow access to entitlement parser

internal/credit/engine.go, internal/credit/grant_connector.go, internal/credit/postgresadapter/grant.go, test/entitlement/regression/framework_test.go, test/entitlement/regression/scenario_test.go
- When querying relevant grants the exclusion criteria for void grants was incorrect
- voidedAt times weren't truncated
=> Hotfix for balance calculation after a grant is voided

internal/credit/balance_connector.go, internal/credit/engine.go, test/entitlement/regression/scenario_test.go
Should fix current error logs
This logic has to be cleaned up, it should apply to all snapshots when saving, and that should happen uniform.
=> Only save balance for active grants during in-between snapshot saves

internal/entitlement/connector.go, internal/entitlement/postgresadapter/entitlement.go
Allows searching by feature key too.
=> feat: allow searching by feature key

api/client/node/clients/feature.ts, api/client/node/clients/subject.ts
Previous argument names suggested functionality that
- currently doesn't exist
- is different from whats in the OpenAPI spec
=> Rename node client arguments to reflect OpenAPI OM-812

ci/main.go
=> ci: dagger cache experiments

.golangci.yaml, internal/ingest/httpingest/httpingest_test.go, internal/ingest/ingestdriver/http_transport_test.go, internal/server/server_test.go
=> ci: add bodyclose linter

api/client/node/package.json, api/client/node/pnpm-lock.yaml
closes [#94](https://github.com/openmeterio/openmeter/security/dependabot/94)
=> chore(sdk): update Node.js dependencies

.github/workflows/ci.yaml
=> ci: run jobs on larger nodes

internal/entitlement/connector.go, internal/productcatalog/feature_connector.go, internal/productcatalog/httpdriver/feature.go, internal/productcatalog/postgresadapter/feature.go, test/entitlement/regression/scenario_test.go
- Fix error on creating new entitlements by a key shared by active and inactive features
Fixes OM-812
=> Fix error on creating new entitlements by a key shared by active and inactive features OM-812

ci/snapshot.go
=> ci: disable stainless for now

cmd/server/main.go, config.example.yaml, config/config.go, config/config_test.go, config/events.go, go.mod, go.sum, internal/credit/events.go, internal/credit/grant_connector.go, internal/entitlement/connector.go, internal/entitlement/entitlement.go, internal/entitlement/metered/connector.go, internal/entitlement/metered/events.go, internal/entitlement/metered/reset.go, internal/entitlement/metered/utils_test.go, internal/event/publisher/publisher.go, internal/event/publisher/transformer.go, internal/event/spec/resourcepath.go, internal/ingest/kafkaingest/namespace.go, internal/watermill/driver/kafka/publisher.go, internal/watermill/driver/noop/publisher.go, openmeter/credit/adapters.go, openmeter/entitlement/adapters.go, openmeter/entitlement/metered/adapters.go, openmeter/event/publisher/publisher.go, pkg/kafka/provisiontopic.go, test/entitlement/regression/framework_test.go
This patch ensures that we are creating kafka events for entitlements changes. Example events:
create entitlement:
```
{
"id": "01J3NQ2GEPKF3GZ36GMPP6MDED",
"source": "//openmeter.io/namespace/default/entitlement/01J3NQ2GENF1RJPXJVVJQR7D4C",
"type": "openmeter.entitlement.v1.createEntitlement",
"subject": "//openmeter.io/namespace/default/subjectKey/subj-2",
"datacontenttype": "application/json",
"time": "2024-07-25T19:49:46.58261Z",
"data": {
"createdAt": "2024-07-25T19:49:46.581756Z",
"updatedAt": "2024-07-25T19:49:46.581756Z",
"id": "01J3NQ2GENF1RJPXJVVJQR7D4C",
"featureId": "01J3N3JYDPCWSRN0ZV4XFJEWHV",
"featureKey": "feature1",
"subjectKey": "subj-2",
"type": "metered",
"usagePeriod": {
"period": "WEEK",
"anchor": "2024-07-25T19:49:00Z"
},
"currentUsagePeriod": …
```
=> feat: add entitlements events

.vscode/launch.json, Dockerfile, Makefile, cmd/balance-worker/.air.toml, cmd/balance-worker/main.go, cmd/balance-worker/version.go, config/balanceworker.go, config/config.go, config/config_test.go, config/events.go, go.mod, go.sum, internal/entitlement/balanceworker/worker.go, internal/event/publisher/publisher.go, internal/event/spec/parser.go
The balance worker will be responsible for emitting balance snapshots. For now we are using the sarama library, but as a seperate PR we will transition to the confluent supported one.
The event handler is unimplemented, so that the application logic will be visible in the seperate PR.
=> feat: skaffold balance worker

.vscode/launch.json, Dockerfile, Makefile, cmd/notification-service/.air.toml, cmd/notification-service/main.go, cmd/notification-service/version.go, config/config.go, config/config_test.go, config/notificationservice.go, internal/notification/consumer/consumer.go, internal/watermill/nopublisher/nopublisher.go
Skaffold notification service.
=> feat: notification-service

internal/entitlement/postgresadapter/entitlement.go
Deleted entitlements weren't excluded from the autoreset which resulted in frequent errors
=> fix: exclude deleted entitlements from autoreset

cmd/balance-worker/main.go, cmd/notification-service/main.go, config/balanceworker.go, config/config_test.go, config/events.go, config/notificationservice.go, internal/entitlement/balanceworker/worker.go, internal/notification/consumer/consumer.go
DLQ (dead letter queue) is a better known term, let's use that in the config
=> refactor: rename poision queue to DLQ

internal/productcatalog/feature_connector.go, internal/productcatalog/postgresadapter/feature.go
=> Pass a list of IDs for exact querying

openmeter/entitlement/httpdriver/handlers.go, openmeter/entitlement/httpdriver/types.go
Exposes missing handler and parameters for cloud to use
=> Expose missing getEntitlementById handler and types

internal/ent/db/balancesnapshot_create.go, internal/ent/db/balancesnapshot_query.go, internal/ent/db/balancesnapshot_update.go, internal/ent/db/ent.go, internal/ent/db/entitlement_create.go, internal/ent/db/entitlement_query.go, internal/ent/db/entitlement_update.go, internal/ent/db/feature_query.go, internal/ent/db/grant_create.go, internal/ent/db/grant_query.go, internal/ent/db/grant_update.go, internal/ent/db/runtime/runtime.go, internal/ent/db/usagereset_create.go, internal/ent/db/usagereset_query.go, internal/ent/db/usagereset_update.go, pkg/framework/entutils/testutils/ent1/db/ent.go, pkg/framework/entutils/testutils/ent1/db/example1_query.go, pkg/framework/entutils/testutils/ent1/db/runtime/runtime.go, pkg/framework/entutils/testutils/ent2/db/ent.go, pkg/framework/entutils/testutils/ent2/db/example2_query.go, pkg/framework/entutils/testutils/ent2/db/runtime/runtime.go
Run Go code generate to update generated code to make it aligned with schemas.
=> fix: go generate for ent schemas

cmd/sink-worker/main.go, config/balanceworker.go, config/config_test.go, config/sink.go, openmeter/sink/flushhandler/ingestnotification/ingestnotification.go, openmeter/watermill/driver/kafka/driver.go
We are also moving the batch size on ingest notification setting to the sink worker because it doesn't make sense on the consumer side.
=> chore: update exports for openmeter

quickstart/quickstart_test.go
Quickstart was broken because of the missing duration property (probably originating from [this change](https://github.com/openmeterio/openmeter/pull/1292/files)).
=> Fix quickstart

cmd/balance-worker/main.go, cmd/notification-service/main.go, cmd/server/main.go, cmd/sink-worker/main.go, internal/watermill/driver/kafka/logger.go, internal/watermill/driver/kafka/publisher.go, internal/watermill/driver/kafka/topic_provision.go, openmeter/watermill/driver/kafka/driver.go
Fixed:
- SASL plain authentication support
- admin client is now the confluent one as sarama doesn't seem to work properly (SASL Auth errors)
=> fix: confluent cloud connectivity issues

internal/registry/builder/entitlement.go, internal/registry/entitlement.go
As that is required by the cloud codebase if we want to move to the registry approach.
=> fix: expose feature repo

openmeter/entitlement/snapshot/events.go, openmeter/watermill/nopublisher/nopublisher.go
Expose types that are needed for the cloud flavor.
=> chore: expose types for cloud usage

internal/entitlement/balanceworker/entitlementhandler.go, openmeter/entitlement/balanceworker/worker.go
Balace worker was using the entitlement.ID instead of the subject key to resolve subject ID.
=> fix: subject ID resolving error

.github/workflows/ci.yaml
=> ci: run ci pipeline on depot

ci/e2e.go, dagger.json
=> ci: update kafka module

README.md
=> docs: tweak readme quickstart

ci/e2e.go, ci/main.go
=> Test improvements

.github/workflows/artifacts.yaml, Dockerfile
=> build: drop ubi and distroless builds

ci/generate.go, ci/main.go, dagger.json
=> build: add container scanning

Dockerfile, ci/versions_pinned.go
Update go version used to build the application
=> build: update go version used to build the application

api/api.gen.go, api/client/go/client.gen.go, api/openapi.yaml, internal/server/router/notification.go
* rename Balance to Value in Payload in order to avoid confusion
* add HTTP endpoint for sending Notification Events
* add HTTP endpoint for Svix [Operational Webhook](https://docs.svix.com/incoming-webhooks) callbacks
=> refactor: Notification API spec

internal/ent/db/notificationchannel_create.go, internal/ent/db/notificationchannel_update.go, internal/notification/channel.go, internal/notification/defaults.go, internal/notification/errors.go, internal/notification/httpdriver/channel.go, internal/notification/httpdriver/errors.go, internal/notification/httpdriver/handler.go, internal/notification/repository.go, internal/notification/repository/entitymapping.go, internal/notification/repository/repository.go, internal/notification/service.go, internal/notification/validator.go
Implement `Channels` support for Notifications API.
Notifications API will be enabled in the HTTP router in a separate PR.
=> feat: implement channels support

internal/notification/httpdriver/handler.go, internal/notification/httpdriver/rule.go, internal/notification/repository.go, internal/notification/repository/entitymapping.go, internal/notification/repository/repository.go, internal/notification/rule.go, internal/notification/service.go
Implement `Rules` for Notifications API.
=> feat: implement rules for Notification API

internal/notification/event.go, internal/notification/eventhandler.go, internal/notification/httpdriver/event.go, internal/notification/httpdriver/handler.go, internal/notification/repository.go, internal/notification/repository/entitymapping.go, internal/notification/repository/repository.go, internal/notification/service.go
Implement `Events` for Notifications API.
=> feat: implement events for Notification API

go.mod, openmeter/entitlement/adapter/adapters.go
Required by cloud deployments to start balance worker.
=> chore: update balance worker adapter

ci/build.go
=> ci: add missing binary builds

ci/e2e.go, ci/main.go, ci/versions_pinned.go, internal/notification/eventhandler.go, test/notification/channel.go, test/notification/event.go, test/notification/helpers.go, test/notification/notification_test.go, test/notification/rule.go, test/notification/testenv.go, test/notification/webhook.go
Add integration test suite for Notification API.
=> test: add integration test suite for Notification API

internal/entitlement/balanceworker/entitlementhandler.go, internal/entitlement/balanceworker/recalculate.go, internal/entitlement/balanceworker/worker.go, internal/entitlement/snapshot/event.go, internal/event/models/models.go, internal/event/models/subject.go, openmeter/entitlement/balanceworker/worker.go, openmeter/event/models/models.go
This patch allows for resolving the full subject entity. This mostly applies for cloud for now, but in case we are introducing entity based subject support into the opensource version it can be useful too.
=> feat: resolve full subject entity

cmd/balance-worker/.air.toml, cmd/notification-service/.air.toml, cmd/server/.air.toml, cmd/sink-worker/.air.toml, flake.nix
=> build: fix kafka linker errors

internal/productcatalog/adapter/feature_test.go
The last test case didn't use the mutex which resulted in intermittent failures.
=> Fix concurrent map writes

.github/workflows/artifacts.yaml, .github/workflows/ci.yaml
Use depot for container image build
=> ci: use depot for container image build

.github/workflows/artifacts.yaml
=> Docker cleanup

internal/notification/event.go
Fix missing payload for notification events.
=> fix: missing payload in notification event

internal/notification/event.go, internal/notification/eventhandler.go, internal/notification/utils.go
Add utils for working with types from Notification API.
=> refactor: add utils for Notification API

internal/entitlement/adapter/entitlement.go
This change makes sure that whenever it's possible, we are filtering by namespace + id for usage_resets so that we are using the appropriate indexes.
Query without namespace:
```
explain SELECT "usage_resets"."id", "usage_resets"."namespace", "usage_resets"."created_at", "usage_resets"."updated_at", "usage_resets"."deleted_at", "usage_resets"."entitlement_id", "usage_resets"."reset_time" FROM "usage_resets" WHERE "usage_resets"."entitlement_id" IN ('01J1Q9K72R4K3DRMSD99XE7YMS') ORDER BY "usage_resets"."reset_time" DESC LIMIT 1;
QUERY PLAN
-------------------------------------------------------------------------------
Limit  (cost=89.66..89.67 rows=1 width=118)
->  Sort  (cost=89.66..89.67 rows=1 width=118)
Sort Key: reset_time DESC
->  Seq Scan on usage_resets  (cost=0.00..89.65 rows=1 …
```
=> refactor: optimize usage reset queries

cmd/balance-worker/main.go, cmd/notification-service/main.go, cmd/server/main.go, test/notification/testenv.go
Fix handling errors returned by database initialization or schema creation.
Bugs were introduced by #1397.
=> fix: database error handling

cmd/notification-service/main.go, internal/event/models/subject.go, internal/notification/consumer/balancethreshold_test.go, internal/notification/consumer/balancetreshold.go, internal/notification/consumer/consumer.go, internal/notification/event.go, internal/notification/repository/repository.go, internal/notification/rule.go, internal/productcatalog/driver/feature.go, internal/productcatalog/driver/parser.go, test/notification/consumer_balance.go, test/notification/notification_test.go
This handler is responsible for creating the notification events based on balance events.
=> feat: notification handler

ci/main.go
ci: separate build cache for quickstart
=> ci: separate build cache for quickstart

internal/notification/consumer/consumer.go
Fixes missing router from notification consumer.
=> fix: notification service startup issues

internal/credit/engine/engine.go, test/entitlement/regression/scenario_test.go
There was an issue in which if the recurrence time was the same as the creation date of the entitlement OR a reset time, we calculated that grant twice
=> Fix bug with recurrence

internal/notification/httpdriver/errors.go, internal/notification/webhook/errors.go, internal/notification/webhook/svix.go, internal/notification/webhook/webhook.go
* fix: properly propagate Svix errors
* feat: allow setting metadata for Svix resources
=> refactor: svix integration in Notification API

internal/notification/repository/repository.go, internal/notification/rule.go, internal/notification/service.go, internal/notification/utils.go, internal/notification/utils_test.go
Fix issue where channels assigned to a rule were not properly updated.
=> fix: update of channel assignment for rules

internal/notification/httpdriver/event.go, internal/notification/repository/entitymapping.go, internal/notification/repository/repository.go, internal/notification/service.go, internal/notification/webhook/webhook.go
* missing metadata on channel udpate
* wrap webhook validation errors
* add debug logging to notification service
* return event timestamps in UTC
* notification event ordering
=> fix: notification api

config.example.yaml, docs/seeder.md, etc/seed/observability.yaml, etc/seed/streams/api-requests.yaml, etc/seed/streams/prompt-tokens.yaml, etc/seed/streams/workload-runtime.yaml
Adds example seeders via benthos streams for the example meters defined in config.
Fixes #(issue)
=> Add example seeders

openmeter/watermill/driver/kafka/metrics/adapter.go
Sarama seems to initialize/get some meters in parallel, this patch ensures that the parallelism is handled properly. Thus avoiding error messages and missing meters during startup of the balance worker.
Also we were doing the wraping twice, the change ensures that we are only doing that once.
=> fix: meter registration

cmd/notification-service/main.go, cmd/server/main.go, openmeter/notification/service.go, test/notification/testenv.go
This causes panics at certain places, let's enforce that the logger is passed in correctly.
Fixes #(issue)
=> fix: nil error on event creation

openmeter/entitlement/balanceworker/recalculate.go
As we have moved to an int64 histogram.
=> fix: remove explicit buckets

openmeter/notification/service/channel.go
Fix bug where updating notification channel resulted in notification rules get unassigned on Svix side due to no rule assignement information passed in update API call.
=> fix: rule assignements lost on channel update

openmeter/entitlement/balanceworker/entitlementhandler.go, openmeter/entitlement/balanceworker/recalculate.go, openmeter/entitlement/balanceworker/worker.go
This patch ensures that we are reporting all calculations performed by the balance worker not just the ones done by the recalculator.
We also expose an end-to-end metric from the jobs, so that we can have a measured upper bound on the job execution times.
=> refactor: balance worker metrics

api/api.gen.go, api/client/go/client.gen.go, api/openapi.yaml, e2e/e2e_test.go
Use common `PaginationInfo` model in API.
=> refactor(api): pagination info

flake.lock, flake.nix
Fix Go 1.23 support
Related golangci/golangci-lint#4837
=> fix: golangci-lint in local env

cmd/server/main.go, openmeter/ingest/ingestadapter/metrics.go, openmeter/ingest/kafkaingest/collector.go
Move collector metrics to a separate middleware as preparation for supporting multiple ingest strategies.
=> refactor: collector meter

config/aggregation.go, config/config_test.go
Make ClickHouse connection params configurable
=> feat(config): clickhouse connection settings

config.example.yaml, config/config.go, config/config_test.go, config/kafka.go, config/testdata/complete.yaml, pkg/kafka/config.go
Consolidate Kafka client configuration.
=> refactor: kafka client configuration

pkg/pgxpoolobserver/observer.go
Make sure we are not doing a division by 0.
=> fix: panic when no pool elements have been acquired

openmeter/meter/meter.go, openmeter/meter/validate.go, openmeter/meter/validate_test.go, openmeter/sink/namespaces.go, openmeter/sink/namespaces_test.go, pkg/models/meter.go
Refactor event validation to make it usable in other places than the sink-worker.
=> Meter event validation

pkg/kafka/config.go, pkg/kafka/config_test.go
Fix incorrect setting of consumer group instance id for Kafka consumer config.
=> fix: Kafka consumer config

dagger.json
=> build: upgrade dagger modules

api/spec/src/cloud/main.tsp, api/spec/src/cloud/subjects.tsp, api/spec/src/entitlements.tsp, api/spec/src/errors.tsp, api/spec/src/main.tsp, api/spec/src/notification.tsp, ci/dev.go, ci/generate.go, dagger.json
=> TypeSpec fixes

openmeter/watermill/driver/kafka/metrics.go
Fixes #(issue)
This decreases the total number of unique label/metricname pairs significantly.
=> fix: use aggregate metrics

openmeter/customer/customer.go, openmeter/customer/errors.go, openmeter/customer/repository.go, openmeter/customer/repository/customer.go, openmeter/customer/service.go, openmeter/ent/db/customer.go, openmeter/ent/db/customer/customer.go, openmeter/ent/db/customer/where.go, openmeter/ent/db/customer_create.go, openmeter/ent/db/customer_update.go, openmeter/ent/db/migrate/schema.go, openmeter/ent/db/mutation.go, openmeter/ent/db/runtime.go, openmeter/ent/schema/customer.go, pkg/framework/entutils/mixins.go, pkg/models/model.go, pkg/timezone/tz.go, tools/migrate/migrations/20240919144910_customer-timezone.down.sql, tools/migrate/migrations/20240919144910_customer-timezone.up.sql, tools/migrate/migrations/atlas.sum
minor refactors + add trivial service implementation
=> refactor: customer features for invoicing

openmeter/customer/customer.go, openmeter/customer/repository.go, openmeter/customer/repository/customer.go, openmeter/customer/service.go
Partial revert of https://github.com/openmeterio/openmeter/pull/1542
Let's use specific types for Parameters so that we can extend them later.
=> refactor: restore dedicated param types

.dagger/versions.go, .dagger/versions_pinned.go, flake.lock, flake.nix, justfile
=> chore: update build dependencies

pkg/framework/transaction/transaction.go
We can just use a default return value and that way we can return non pointer values.
=> Remove unnecessary pointer return from transaction.Run

.dagger/generate.go, .dagger/lint.go, api/spec/package.json
=> Add lint job for TypeSpec

.dagger/ci.go, .github/workflows/artifacts.yaml
Temporary fix for aquasecurity/trivy-action#389
=> ci: use trivy db mirror to avoid rate limit

api/spec/src/notification/channel.tsp, api/spec/src/notification/rule.tsp
Fix TypeSpec dfefinition of update endpoints for Notification API.
=> fix(api): update endpoints for Notification API

cmd/server/main.go, cmd/sink-worker/main.go, openmeter/ingest/kafkaingest/collector.go, openmeter/ingest/kafkaingest/namespace.go, openmeter/ingest/kafkaingest/topicresolver/namespacedtopic.go, openmeter/ingest/kafkaingest/topicresolver/resolver.go, openmeter/sink/sink.go
Make resolving namespaces to Kafka topic names pluggable.
=> feat: add Kafka topic name resolver

openmeter/productcatalog/adapter/feature.go
Fix db query for listing features by multiple ids or keys.
=> fix: list features by multiple Ids or Keys

api/spec/src/notification/channel.tsp, api/spec/src/notification/rule.tsp
fix: typespec openapi diff in notifications
=> fix: typespec openapi diff in notifications

api/spec/src/entitlements/entitlements.tsp
fix: typo in entitlements typespec
=> fix: typo in entitlements typespec

openmeter/entitlement/adapter/entitlement.go, openmeter/entitlement/adapter/usage_reset.go, pkg/framework/entutils/transaction.go
Removes bogus nil shenanigans.
=> Use default returns for TX Repo helpers

cmd/balance-worker/main.go, cmd/notification-service/main.go, cmd/server/main.go, cmd/sink-worker/main.go
fix: exit if application initialization fails
=> fix: exit if application initialization fails

config/config.go, config/telemetry.go
=> chore: expose telemetry config

cmd/balance-worker/wire.go, cmd/notification-service/wire.go, cmd/server/wire.go, cmd/sink-worker/wire.go, cmd/sink-worker/wire_gen.go, openmeter/app/wire.go
move config to a different wire set
=> refactor: move config to a different wire set

.dagger/main.go
fix: run pnpm install when necessary
=> fix: run pnpm install when necessary

justfile
=> add generate target to just

cmd/balance-worker/main.go, cmd/notification-service/main.go, cmd/sink-worker/main.go, config/config_test.go, config/ingest.go, config/testdata/complete.yaml, config/topicprovisioner.go, config/viper.go, openmeter/app/kafka.go
* add service config for `TopicProvisioner`
* add `ViperKeyPrefixer` helper for templating config paramter names
=> refactor: topic provisioner config

api/client/go/client.go
=> fix: Go client gen

cmd/balance-worker/main.go, cmd/balance-worker/wire.go, cmd/balance-worker/wire_gen.go, cmd/notification-service/main.go, cmd/notification-service/wire.go, cmd/notification-service/wire_gen.go, cmd/server/main.go, cmd/server/wire.go, cmd/server/wire_gen.go, cmd/sink-worker/main.go, cmd/sink-worker/wire.go, cmd/sink-worker/wire_gen.go, openmeter/app/globals.go, openmeter/app/kafka.go, openmeter/app/telemetry.go, openmeter/app/wire.go
Move some more services into wire
=> Wire refactor round 2

cmd/balance-worker/wire_gen.go, cmd/notification-service/wire_gen.go, cmd/server/wire_gen.go, cmd/sink-worker/wire_gen.go, openmeter/app/kafka.go
fix: use kafka configuration to create admin client
=> fix: use kafka configuration to create admin client

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/sdk-node.yaml, .github/workflows/sdk-python.yaml, .github/workflows/sdk-web.yaml, .github/workflows/snapshot.yaml, dagger.json, flake.lock
=> build: update dagger

.github/workflows/ci.yaml
=> ci: try ci

.github/workflows/ci.yaml
=> Try new runners

cmd/balance-worker/main.go, cmd/balance-worker/wire.go, cmd/balance-worker/wire_gen.go, cmd/notification-service/main.go, cmd/notification-service/wire.go, cmd/notification-service/wire_gen.go, cmd/server/main.go, cmd/server/wire.go, cmd/server/wire_gen.go, cmd/sink-worker/main.go, cmd/sink-worker/wire.go, cmd/sink-worker/wire_gen.go, openmeter/app/app.go, openmeter/app/telemetry.go, openmeter/app/watermill.go, openmeter/app/wire.go
=> refactor: otel initialization

.github/workflows/ci.yaml
Disabling Dagger Cloud to see if it fixes hanging CI builds
Related dagger/dagger#8697
=> ci: disable dagger cloud

.github/workflows/ci.yaml
=> ci: enable dagger cloud

.github/workflows/ci.yaml
=> ci: disable new runners

cmd/balance-worker/main.go, cmd/balance-worker/wire.go, cmd/balance-worker/wire_gen.go, cmd/notification-service/main.go, cmd/notification-service/wire.go, cmd/notification-service/wire_gen.go, cmd/server/wire.go, cmd/server/wire_gen.go, cmd/sink-worker/main.go, cmd/sink-worker/wire.go, cmd/sink-worker/wire_gen.go, config/config_test.go, config/telemetry.go, openmeter/app/openmeter.go, openmeter/app/openmeter_provisiontopics.go, openmeter/app/telemetry.go, openmeter/app/watermill.go, openmeter/app/wire.go
Move additional initialization code inside wire
=> Wire refactor round 3

app/common/app.go, app/common/openmeter_balanceworker.go, app/common/openmeter_provisiontopics.go, app/common/wire.go, cmd/balance-worker/main.go, cmd/balance-worker/wire.go, cmd/balance-worker/wire_gen.go
Finish wire refactor in balance worker
=> Finish wire refactor in balance worker

openmeter/entitlement/adapter/entitlement.go
Scheduling resulted in an error if the user had entitlements for multiple features due to a missing filter.
=> Fixes entitlement creation

app/config/config_test.go, app/config/sink.go, cmd/sink-worker/main.go, openmeter/sink/sink.go, pkg/kafka/config.go
Extend sink config.
Remove in code legacy defaults.
=> feat(sink): extends poll config

openmeter/sink/sink.go
Validate config in sink internal.
=> feat(sink): config validation

app/config/config_test.go, app/config/sink.go, cmd/sink-worker/main.go, openmeter/sink/storage.go
Make ClickHouse async insert configurable.
=> feat(sink): make async insert configurable

api/spec/.prettierrc.json, api/spec/lib/rules/casing.js, api/spec/lib/rules/docs.js, api/spec/lib/rules/friendlyName.js, api/spec/src/app/marketplace.tsp, api/spec/src/app/stripe.tsp, api/spec/src/billing/invoices.tsp, api/spec/src/billing/profile.tsp, api/spec/src/cloud/main.tsp, api/spec/src/cloud/subjects.tsp, api/spec/src/customer.tsp, api/spec/src/entitlements/entitlements.tsp, api/spec/src/entitlements/feature.tsp, api/spec/src/entitlements/subjects.tsp, api/spec/src/events.tsp, api/spec/src/meters.tsp, api/spec/src/notification/channel.tsp, api/spec/src/notification/event.tsp, api/spec/src/notification/rule.tsp, api/spec/src/portal.tsp, api/spec/src/productcatalog/ratecards.tsp, api/spec/src/productcatalog/routes.tsp, api/spec/src/types.tsp
=> chore(api): update typespec prettier config

app/config/config_test.go, app/config/sink.go, cmd/sink-worker/main.go, openmeter/sink/storage.go
Make sink storage insert query settings configurable.
=> feat(sink): query settings

app/common/telemetry.go, cmd/jobs/service/otel.go, cmd/sink-worker/wire.go, cmd/sink-worker/wire_gen.go, go.mod, go.sum
=> chore: update otelslog

openmeter/app/adapter/adapter.go, openmeter/app/adapter/app.go, openmeter/app/stripe/adapter/adapter.go, openmeter/app/stripe/adapter/customer.go, openmeter/app/stripe/adapter/stripe.go, openmeter/customer/adapter/adapter.go, openmeter/customer/adapter/app.go, openmeter/customer/adapter/customer.go
Transactions were previously ignored by the package due to this.
=> Use transacting repos for customer package

openmeter/ingest/ingestadapter/metrics.go
Prefix ingest metrics with `openmeter.`.
Kept the old metrics in this instance. We can remove them after a deprecation period.
=> refactor(ingest): prefix metrics with openmeter

openmeter/app/stripe/adapter/stripe.go, openmeter/app/stripe/entity/app/app.go, openmeter/secret/adapter/secret.go, openmeter/secret/entity/secret.go
Add key and app id to secret id
=> feat(secret): add app id and key to secret id

api/api.gen.go, api/openapi.yaml, api/spec/src/billing/invoices.tsp, api/spec/src/billing/invoices/invoice.tsp, openmeter/server/router/billing.go
Rename the /workflow/approve to /approve (as it's better aligned with the other endpoints)
Add /retry to retry failed actions after fixing the issues
Due to [invoice states PR](https://github.com/openmeterio/openmeter/pull/1766) now it's visible how the invoice's status field will be handled:
- The field will only contain the main status (`draft`, `issuing`, etc)
- A statusDetails field will contain the immutability flags, failure flags, extended status value, plus the list of available actions.
=> feat: add invoice workflow management API changes

pkg/recurrence/recurrence_test.go
=> test(recurrance): fix flaky

app/config/telemetry.go, go.mod, go.sum
Support Stdout OTel Log exporter. Useful for local testing.
=> feat(telemetry): log exporter stdout

pkg/kafka/log.go
Map Informal Kafka logs to Debug.
=> feat(kafka): reduce verbosity of kafka logs

app/config/postgres.go
Defaults need to be set here for `viper.AutomaticEnv` to work.
Fixes #(issue)
=> Fix env parsing for POISTGRES_URL

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/sdk-node.yaml, .github/workflows/sdk-python.yaml, .github/workflows/sdk-web.yaml, .github/workflows/snapshot.yaml, Makefile
Seems like we have an integration issue with Dagger Cloud. Temporarily disabling reporting until the issue has been sorted out.
Reverting this PR reproduces the issue, we can use that to validate any solution.
=> chore: disable dagger cloud

openmeter/productcatalog/plan/adapter/adapter.go, openmeter/productcatalog/plan/adapter/phase.go, openmeter/productcatalog/plan/adapter/plan.go, openmeter/productcatalog/plan/httpdriver/mapping.go, openmeter/productcatalog/plan/httpdriver/phase.go, openmeter/productcatalog/plan/httpdriver/plan.go, openmeter/productcatalog/plan/repository.go, openmeter/productcatalog/plan/service/phase.go, openmeter/productcatalog/plan/service/plan.go
Add database transaction support to Plan API.
=> refactor: add TX support to Plan API

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/sdk-node.yaml, .github/workflows/sdk-python.yaml, .github/workflows/sdk-web.yaml, .github/workflows/snapshot.yaml, Makefile
Reverts openmeterio/openmeter#1806
=> Revert "chore: disable dagger cloud"

openmeter/billing/httpdriver/invoiceline.go, openmeter/productcatalog/plan/adapter/adapter_test.go, openmeter/productcatalog/plan/adapter/mapping.go, openmeter/productcatalog/plan/adapter/phase.go, openmeter/productcatalog/plan/adapter/plan.go, openmeter/productcatalog/plan/errors.go, openmeter/productcatalog/plan/httpdriver/mapping.go, openmeter/productcatalog/plan/plan.go, openmeter/productcatalog/plan/plan_test.go, openmeter/productcatalog/plan/price.go, openmeter/productcatalog/plan/price_test.go, openmeter/productcatalog/plan/ratecard.go, openmeter/productcatalog/plan/service.go, openmeter/productcatalog/plan/service/plan.go, openmeter/productcatalog/plan/service/service.go, openmeter/productcatalog/plan/service/service_test.go
Fix multiple bugs/issues related to Plan API like:
* missing `Feature` validation for RateCards
* publishing/archiving Plans
* creating new version for Plan
=> fix: multiple issues in Plan API

app/common/app.go, cmd/balance-worker/wire.go, cmd/balance-worker/wire_gen.go, cmd/notification-service/wire.go, cmd/notification-service/wire_gen.go, cmd/server/wire.go, cmd/server/wire_gen.go, cmd/sink-worker/wire.go, cmd/sink-worker/wire_gen.go
Service name as `openmeter` for all services.
=> fix(telemetry): service name

openmeter/productcatalog/plan/adapter/phase.go, openmeter/productcatalog/plan/httpdriver/mapping.go
* `PaymentTerm` mapping in http driver
*  updating `TaxConfig` and `Price` attributes for `RateCard`
=> fix: Plan API

openmeter/productcatalog/plan/discount.go, openmeter/productcatalog/plan/discount_test.go, openmeter/productcatalog/plan/httpdriver/mapping.go
Fix JSON serialization of `Plan.Discount`.
=> fix: Plan Discount JSON serialization

openmeter/entitlement/boolean/connector.go, openmeter/entitlement/connector.go, openmeter/entitlement/entitlement_types.go, openmeter/entitlement/metered/connector.go, openmeter/entitlement/static/connector.go, openmeter/entitlement/utils_test.go
Use context in entitlement get value
=> feat(entitlement): pass context to get value

app/common/watermill.go, openmeter/billing/adapter/invoice.go, openmeter/billing/adapter/profile.go, openmeter/billing/service/invoice.go, openmeter/billing/service/invoiceline.go, openmeter/customer/adapter/customer.go, openmeter/entitlement/balanceworker/ingesthandler.go, openmeter/ingest/kafkaingest/collector.go, openmeter/notification/consumer/balancetreshold.go, openmeter/notification/eventhandler/handler.go, openmeter/notification/repository/channel.go, openmeter/notification/repository/event.go, openmeter/notification/repository/rule.go, openmeter/notification/webhook/webhook.go, openmeter/productcatalog/plan/adapter/phase.go, openmeter/productcatalog/plan/adapter/plan.go, openmeter/sink/flushhandler/handler.go, openmeter/sink/flushhandler/ingestnotification/handler.go, openmeter/sink/sink.go, pkg/kafka/topicprovisioner.go
Log with context so we have more information like HTTP request attrs in routes.
=> feat(log): with context

.dagger/versions_pinned.go, docker-compose.yaml, go.mod, go.sum, openmeter/notification/webhook/svix.go, openmeter/notification/webhook/webhook.go
Bump Svix to v1.40.0 and adopt the breaking changes this version introduced.
=> chore(deps): bump Svix to v1.40.0

.github/workflows/sdk-node.yaml, .github/workflows/sdk-python.yaml, .github/workflows/sdk-web.yaml, .github/workflows/snapshot.yaml
Fix Dagger version for Snapshot and SDK workflows.
=> ci: fix Dagger version for Snapshot and SDK workflows

openmeter/productcatalog/plan/adapter/phase.go, openmeter/productcatalog/plan/service/service_test.go
Fix issue where updating a Plan Phase to have no RateCards is not properly applied.
=> fix: updating PlanPhase to have no RateCards

openmeter/productcatalog/plan/adapter/plan.go, openmeter/productcatalog/plan/service/service_test.go
Fix issue where updating a Plan to have no PlanPhases is not properly applied.
=> fix: updating Plan to have no PlanPhases

openmeter/productcatalog/plan/adapter/phase.go, openmeter/productcatalog/plan/assert.go, openmeter/productcatalog/plan/service/phase.go, openmeter/productcatalog/plan/service/service_test.go
Ensure that staus of Plan is validated/checked for PlanPhase operations to avoid incompatible/prohibited changes made to Plan.
=> fix: Plan status check at PlanPhase operations

openmeter/productcatalog/plan/adapter/plan.go, openmeter/productcatalog/plan/service.go
Remove option for hard deleting resources in Plan API.
=> refactor: rm unused hard delete option

openmeter/productcatalog/plan/httpdriver/mapping.go, openmeter/productcatalog/plan/service.go
Fix Plan, PlanPhase identifier mapping in create/update requests.
=> fix: Plan/Phase request mapping in HTTP driver

openmeter/productcatalog/plan/httpdriver/idorkey.go, openmeter/productcatalog/plan/httpdriver/mapping.go, openmeter/productcatalog/plan/httpdriver/plan.go, openmeter/productcatalog/plan/price.go, openmeter/productcatalog/plan/service/plan.go, openmeter/server/router/plan.go
* fix listing deleted Plans
* fix setting default PaymentTerm for FlatPrice if not provided
* fix getting Plan by ID or Key
* fix creating new Plan version
=> fix: Plan API implementation

openmeter/ent/db/migrate/schema.go, openmeter/ent/schema/productcatalog.go, openmeter/productcatalog/plan/adapter/plan.go, tools/migrate/migrations/20241119154436_plan.down.sql, tools/migrate/migrations/20241119154436_plan.up.sql, tools/migrate/migrations/atlas.sum
* fix returning deleted PlanPhases which is not desired
* fix unique index so repalcing PlanPhase does not result in SQL contraint violation as long as the `deleted_at` field is unique
=> fix: listing deleted PlanPhases

openmeter/customer/adapter/customer.go, openmeter/ent/db/customersubjects.go, openmeter/ent/db/customersubjects/customersubjects.go, openmeter/ent/db/customersubjects/where.go, openmeter/ent/db/customersubjects_create.go, openmeter/ent/db/customersubjects_update.go, openmeter/ent/db/migrate/schema.go, openmeter/ent/db/mutation.go, openmeter/ent/db/runtime.go, openmeter/ent/db/setorclear.go, openmeter/ent/schema/customer.go, test/customer/customer.go, tools/migrate/migrations/20241119181140_customer_subjects_soft_delete.down.sql, tools/migrate/migrations/20241119181140_customer_subjects_soft_delete.up.sql, tools/migrate/migrations/atlas.sum
Delete customer subject relations so another customer can reuse the subject.
=> fix(customer): delete customer subjects

openmeter/customer/entity/customer.go
=> fix(customer): api mapping

openmeter/productcatalog/plan/adapter/mapping.go, openmeter/productcatalog/plan/adapter/phase.go, openmeter/productcatalog/plan/adapter/plan.go, openmeter/productcatalog/plan/httpdriver/mapping.go, openmeter/productcatalog/plan/phase.go, openmeter/productcatalog/plan/service.go, openmeter/productcatalog/plan/service/service.go, openmeter/productcatalog/plan/utils.go, openmeter/productcatalog/plan/utils_test.go
Add support for Discount to Plan API.
=> feat: add Discount support to Plan API

openmeter/billing/adapter/invoicelinediff.go, openmeter/billing/adapter/invoicelines.go, pkg/set/set.go, pkg/set/set_test.go
Add locking support to the set. This allows parallel use, and decreases the amount of possible suprises when we start to use it like that.
=> refactor: lockable set

api/api.gen.go, api/openapi.yaml, api/spec/src/productcatalog/routes.tsp, api/spec/src/productcatalog/subscription.tsp, api/spec/src/types.tsp, openmeter/server/router/subscription.go
- Adds route for changing subscription
- Changes "Create" signature to accept custom plan input
=> Refactor Subscription Routes

openmeter/billing/adapter/invoice.go, openmeter/billing/entity/errors.go, openmeter/billing/entity/invoice.go, openmeter/billing/invoice.go, openmeter/billing/service.go, openmeter/billing/service/invoice.go, openmeter/billing/service/invoicestate.go, openmeter/ent/db/billinginvoice/billinginvoice.go, openmeter/ent/db/migrate/schema.go, test/billing/invoice_test.go
Invoice deletion is performed by state machine transitions allowing us the notify the apps to make the necessary changes on the external system side.
=> feat: delete invoice

api/api.gen.go, api/openapi.cloud.yaml, api/openapi.yaml, api/spec/src/billing/invoices.tsp, api/spec/src/billing/invoices/invoice.tsp, api/spec/src/cloud/main.tsp, openmeter/billing/httpdriver/handler.go, openmeter/billing/httpdriver/invoice.go, openmeter/billing/httpdriver/invoiceline.go, openmeter/billing/invoice.go, openmeter/billing/invoiceline.go, openmeter/billing/service.go, openmeter/billing/service/invoice.go, openmeter/billing/service/invoiceline.go, openmeter/server/router/billing.go, test/billing/invoice_test.go
This patch removes the customer parts. The invoice line creation for existing invoices will be done in a seperate PR as that needs to align with the invoice update setup.
=> refactor: billing api drop customer parts

openmeter/subscription/repo/mapping.go
PlanRef isn't properly optional yet (coming soon) which resulted in a panic, lets avoid that in the meantime.
=> Fix Subs panic on nil plan

openmeter/productcatalog/ratecard.go, openmeter/productcatalog/subscription/plan.go
Contrary to the branch name, it exposes the `BillingCadence` through the `RateCard` interface
=> Expose BillingCadence for all RateCards

openmeter/entitlement/metered/connector.go, openmeter/subscription/service/service_test.go, openmeter/subscription/subscriptionspec.go
Truncate when using the internal APIs too
=> Truncate Subscription Entitlement start times

app/common/subscription.go, cmd/server/wire_gen.go, openmeter/billing/worker/subscription/scanario_test.go, openmeter/customer/entity/customer.go, openmeter/event/metadata/resourcepath.go, openmeter/subscription/events.go, openmeter/subscription/item.go, openmeter/subscription/phase.go, openmeter/subscription/ratecard.go, openmeter/subscription/service/service.go, openmeter/subscription/service/update.go, openmeter/subscription/subscription.go, openmeter/subscription/subscriptionspec.go, openmeter/subscription/subscriptionview.go, openmeter/subscription/testutils/service.go, pkg/models/id.go, pkg/models/model.go
Example created event:
```
{
"id": "01JF83TDXR4ECC7YCZCG7RJYF4",
"source": "//openmeter.io/namespace/default/subscription/01JF83TDX4HASRYJS0NZQYQ6NZ",
"type": "io.openmeter.subscription.v1.subscription.created",
"subject": "//openmeter.io/namespace/default/customer/01JF83T7EZDDYQ9YAA3FNBRCQH",
"datacontenttype": "application/json",
"time": "2024-12-16T16:11:33.176382Z",
"data": {
"subscription": {
"namespace": "default",
"id": "01JF83TDX4HASRYJS0NZQYQ6NZ",
"createdAt": "2024-12-16T16:11:33.156461Z",
"updatedAt": "2024-12-16T16:11:33.156462Z",
"activeFrom": "2024-12-16T16:00:00Z",
"activeTo": null,
"name": "subscription-name",
"planRef": {
"id": "01JF83FX50BE258VDMNRBHNPMG",
"key": "test",
"version": 1
},
"customerId": "01JF83T7EZDDYQ9YAA3FNBRCQH",
"currency": "USD" …
```
=> feat: add subscription events

.vscode/launch.json, app/common/billing.go, app/common/openmeter_billingworker.go, cmd/billing-worker/wire_gen.go, cmd/server/main.go, cmd/server/wire_gen.go, openmeter/billing/defaults.go, openmeter/billing/httpdriver/defaults.go, openmeter/billing/httpdriver/profile.go, openmeter/billing/service.go, openmeter/billing/service/profile.go, openmeter/billing/worker/worker.go
This patch ensures that:
- We autoprovision a default billing profile if does not exists
- We handle subscription events
=> feat: wire in subscription events

openmeter/billing/adapter/invoicelines.go, openmeter/billing/httpdriver/invoice.go, openmeter/billing/invoice.go, openmeter/billing/invoiceline.go, openmeter/billing/service/invoice.go, openmeter/billing/service/invoicecalc/details.go, openmeter/billing/service/lineservice/linebase.go, test/billing/invoice_test.go
For gathering invoices we recalculate the lines, so that we can show consistent results. This is a temporary measure until we have a more robust implementation in place.
=> feat: recalculate gathering invoices

openmeter/billing/adapter/invoicelinediff_test.go, openmeter/billing/adapter/invoicelinemapper.go, openmeter/billing/adapter/invoicelines.go, openmeter/billing/httpdriver/invoiceline.go, openmeter/billing/invoice.go, openmeter/billing/invoiceline.go, openmeter/billing/service/lineservice/usagebasedline.go, openmeter/billing/service/lineservice/usagebasedline_test.go, openmeter/billing/worker/subscription/sync.go, test/app/stripe/invoice_test.go, test/app/stripe/testenv.go, test/billing/adapter_test.go, test/billing/invoice_test.go
Add a complex invoicing testcase for stripe validation. As a side-effect the patch fixes the json marshaling errors for the invoicing subsystem.
=> test: add stripe invoicing testcase

pkg/kafka/metrics/broker.go, pkg/kafka/metrics/consumergroup.go, pkg/kafka/metrics/metrics.go, pkg/kafka/metrics/topic.go
Fix reporting invalid values for metrics with Counter type by changing meter type from Counter to Gauge.
=> fix: Kafka metrics

api/api.gen.go, api/client/go/client.gen.go, api/client/node/schemas/openapi.ts, api/client/web/src/client/openapi.ts, api/openapi.cloud.yaml, api/openapi.yaml, api/spec/src/app/stripe.tsp, openmeter/app/stripe/adapter.go, openmeter/app/stripe/adapter/stripe.go, openmeter/app/stripe/client/stripe.go, openmeter/app/stripe/entity/input.go, openmeter/app/stripe/httpdriver/apikey.go, openmeter/app/stripe/httpdriver/handler.go, openmeter/app/stripe/service.go, openmeter/app/stripe/service/app.go, openmeter/app/stripe/service/factory.go, openmeter/secret/adapter.go, openmeter/secret/adapter/secret.go, openmeter/secret/entity/input.go, openmeter/secret/service.go, openmeter/secret/service/secret.go, openmeter/server/router/appstripe.go, openmeter/server/server_test.go, test/app/stripe/app_test.go, test/app/stripe/appstripe.go, test/app/stripe/secret_mock.go, test/app/stripe/testenv.go
=> feat(stripe): update api key

openmeter/app/adapter.go, openmeter/app/adapter/app.go, openmeter/app/entity/app.go, openmeter/app/errors.go, openmeter/app/service.go, openmeter/app/service/app.go, openmeter/app/stripe/adapter.go, openmeter/app/stripe/adapter/adapter.go, openmeter/app/stripe/adapter/customer.go, openmeter/app/stripe/adapter/stripe.go, openmeter/app/stripe/client/appclient.go, openmeter/app/stripe/client/client.go, openmeter/app/stripe/client/invoice.go, openmeter/app/stripe/client/invoice_line.go, openmeter/app/stripe/client/logger.go, openmeter/app/stripe/client/stripe_app_client.go, openmeter/app/stripe/client/stripe_client.go, openmeter/app/stripe/entity/app/app.go, openmeter/app/stripe/entity/app/client.go, openmeter/app/stripe/service/factory.go, openmeter/app/stripe/service/service.go, openmeter/server/server_test.go, test/app/stripe/appstripe.go, test/app/stripe/fixture.go, test/app/stripe/invoice_test.go, test/app/stripe/stripe_mock.go, test/app/stripe/testenv.go
- Separate Stripe Client into two: 1. for installed app, 2. for non-installed apps
- Update app status to unauthorized when stripe unauthorized error happens
- Update app status to ready at install and update API key
- Explicit Stripe client mocks
=> feat(app): stripe status

.dagger/versions_pinned.go, docker-compose.yaml, go.mod, go.sum, openmeter/notification/webhook/svix.go, openmeter/notification/webhook/webhook.go
=> chore: bump Svix to 1.44

.dagger/versions.go, .dagger/versions_pinned.go, Dockerfile, benthos-collector.Dockerfile
Bump build and CI dependencies.
=> chore: bump build/ci dependencies

openmeter/watermill/driver/kafka/broker.go
Test potential memory/goroutine leak.
=> refactor: disable Sarama metric collection

openmeter/watermill/driver/kafka/broker.go
Reverts openmeterio/openmeter#2007
=> Revert "refactor: disable Sarama metric collection"

openmeter/app/httpdriver/marketplace.go, openmeter/billing/adapter/profile.go, openmeter/billing/errors.go, openmeter/billing/profile.go, openmeter/billing/service/profile.go, test/billing/profile_test.go
- Update overrides default
- Update doesn't allow to don't have default billing profile
=> feat(billing): profile default update

openmeter/credit/balance.go, openmeter/credit/grant.go, openmeter/entitlement/connector.go, openmeter/entitlement/driver/entitlement.go, openmeter/entitlement/driver/metered.go, openmeter/entitlement/metered/balance.go, openmeter/entitlement/metered/grant_owner_adapter.go, openmeter/entitlement/scheduling.go, openmeter/productcatalog/feature/connector.go, openmeter/productcatalog/plan/service/plan.go, openmeter/productcatalog/subscription/service/change.go, openmeter/productcatalog/subscription/service/create.go, openmeter/productcatalog/subscription/service/migrate.go, openmeter/productcatalog/subscription/service/plan.go, openmeter/subscription/service/service.go, openmeter/subscription/service/workflowservice.go, pkg/models/error.go
Instead of just passing messages its better to wrap the original errors
=> Use error wrapping for generic errors

e2e/productcatalog_test.go, openmeter/productcatalog/subscription/http/mapping.go
=> Fix Subscription Status mapping

openmeter/billing/adapter/invoice.go, openmeter/billing/httpdriver/invoice.go, openmeter/billing/invoice.go, openmeter/billing/service/invoiceline.go, openmeter/billing/worker/subscription/scanario_test.go, test/billing/invoice_test.go
Add support for multiple namespaces to `ListInvoices` API.
=> feat: support listing invoices across namespaces

openmeter/productcatalog/subscription/http/errors.go, openmeter/subscription/service/workflowservice.go
=> Add missing errors to HTTP mappings

openmeter/billing/worker/worker.go, openmeter/entitlement/balanceworker/worker.go, openmeter/notification/consumer/consumer.go, openmeter/watermill/grouphandler/grouphandler.go
=> feat(balance-worker): add additional handlers

openmeter/app/httpdriver/app.go, openmeter/app/httpdriver/customer.go, openmeter/app/httpdriver/handler.go, openmeter/app/httpdriver/mapper.go, openmeter/app/httpdriver/marketplace.go, openmeter/app/stripe/adapter.go, openmeter/app/stripe/adapter/stripe.go, openmeter/app/stripe/service.go, openmeter/app/stripe/service/app.go, openmeter/billing/httpdriver/handler.go, openmeter/billing/httpdriver/invoice.go, openmeter/billing/httpdriver/profile.go, openmeter/server/router/router.go, openmeter/server/server_test.go
Resolve masked API key in HTTP Driver.
=> fix(app): masked api key in http handler

openmeter/billing/adapter/invoice.go, openmeter/billing/adapter/profile.go, test/billing/profile_test.go
=> feat(billing): app used check invoice states

openmeter/billing/subscription/validator.go
Return Conflict errors instead of generic errors.
Fixes [OM-1101: Validate App & Customer](https://linear.app/openmeter/issue/OM-1101/validate-app-and-customer)
=> BillingValidation Error Mapping

Makefile, cmd/jobs/billing/advance/advance.go, cmd/jobs/billing/billing.go, cmd/jobs/main.go, openmeter/billing/adapter/invoice.go, openmeter/billing/invoice.go, openmeter/billing/worker/advance/advance.go
Add suport for advancing invoices to `job` cli which can be periodically run as a batch process.
=> feat: add invoice advance job

openmeter/app/adapter/app.go, openmeter/app/adapter/customer.go, test/app/stripe/appstripe.go
Fixing to list customer app data with deleted customer app data.
=> fix(app): handle customer data deleted at

openmeter/subscription/service/service.go, openmeter/subscription/service/service_test.go
- check currencies are matching when present
- set currency on customer if unset
=> Add currency checks on Subs creation

openmeter/subscription/subscriptionview.go
No items were returned due to a mapping error
=> Add missing items

openmeter/billing/worker/subscription/phaseiterator.go, openmeter/billing/worker/subscription/sync.go, openmeter/billing/worker/subscription/sync_test.go
We want to give the users more control about when to pro-rate, so we are disabling this feature for now.
=> fix: disable pro rating

openmeter/subscription/patch/patch_test.go, openmeter/subscription/patch/stretchphase.go, openmeter/subscription/patch/stretchphase_test.go, openmeter/subscription/testutils/compare.go
Fixes bugs related to phase stretching.
=> Fix Phase Stretching

openmeter/billing/service/invoicecalc/calculator.go, openmeter/billing/service/invoicecalc/period.go
We are calculating the period value of the invoice based on the line items min/max period values.
=> feat: implement period value calculation of the invoice

.envrc, flake.lock
* bump direnv
* update nix environment
=> chore: bump nix

openmeter/app/stripe/client/appclient.go, openmeter/app/stripe/client/invoice_line.go, openmeter/app/stripe/entity/app/invoice.go, openmeter/billing/httpdriver/invoiceline.go, openmeter/billing/invoice.go, test/app/stripe/invoice_test.go, test/app/stripe/stripe_mock.go
This patch makes sure that our stripe app handles taxBehavior and taxCode properly, by moving to the InvoiceItem API of stripe.
Besides that it also fixes issues with invoice edit/update.
=> feat: add support for tax included and tax code settings on invoices

api/api.gen.go, api/client/go/client.gen.go, api/client/javascript/src/client/schemas.d.ts, api/openapi.cloud.yaml, api/openapi.yaml, api/spec/src/app/app.tsp, api/spec/src/billing/customeroverride.tsp, api/spec/src/billing/invoices.tsp, api/spec/src/billing/invoices/docref.tsp, api/spec/src/billing/invoices/invoice.tsp, api/spec/src/billing/profile.tsp, api/spec/src/productcatalog/plan.tsp, api/spec/src/productcatalog/prices.tsp, api/spec/src/types.tsp, openmeter/billing/httpdriver/invoice.go, openmeter/billing/httpdriver/invoiceline.go
This patch fixes billing related warning in the code and make sure that we are adhering to the naming standards of the rest of the API.
=> fix: uppercase names

openmeter/app/stripe/adapter/customer.go, openmeter/app/stripe/adapter/stripe.go, openmeter/app/stripe/client/appclient.go, openmeter/app/stripe/client/stripe.go, openmeter/app/stripe/entity/input.go
Pass openmeter customer email to Stripe if set.
=> feat(app): pass email in stripe checkout session customer create

pkg/recurrence/recurrence.go, pkg/recurrence/recurrence_test.go
There was a date calculation bug, due to which it broke on jan 29th
=> Fix recurrence

openmeter/productcatalog/adapter/feature.go, openmeter/productcatalog/adapter/feature_test.go
Filtering in the edge query doesn't filter the full row, only whether the edge is loaded
Fixes https://discord.com/channels/1115196678169952296/1334021867564175391
=> Fix Feature Archivation Checks

openmeter/entitlement/boolean/connector.go, openmeter/entitlement/entitlement.go, openmeter/entitlement/metered/connector.go, openmeter/entitlement/static/connector.go, openmeter/productcatalog/entitlement.go, pkg/recurrence/recurrence.go, tools/migrate/migrations/20250129143720_minimum-entitlement-usageperiod.up.sql, tools/migrate/migrations/atlas.sum
We didn't have any validations for how long or short the UsagePeriod can be.
The migration will soft-delete any such items & ratecards in the DB as otherwise they would be bricked when parsing
=> Disallow items with periods less than 1 hour

openmeter/billing/adapter/invoice.go, openmeter/billing/invoice.go, openmeter/billing/service/collectionat.go, openmeter/billing/service/invoice.go, openmeter/billing/service/invoiceline.go, openmeter/ent/db/billinginvoice.go, openmeter/ent/db/billinginvoice/billinginvoice.go, openmeter/ent/db/billinginvoice/where.go, openmeter/ent/db/billinginvoice_create.go, openmeter/ent/db/billinginvoice_update.go, openmeter/ent/db/migrate/schema.go, openmeter/ent/db/mutation.go, openmeter/ent/db/runtime.go, openmeter/ent/db/setorclear.go, openmeter/ent/schema/billing.go, test/billing/invoice_test.go, tools/migrate/migrations/20250130104722_billing-collection-at.down.sql, tools/migrate/migrations/20250130104722_billing-collection-at.up.sql, tools/migrate/migrations/atlas.sum
Introduce `collectionAt` attribute for invoices which is used to mark the expected collection of items from gathering invoice.
=> feat(billing): add collectionAt to invoices

openmeter/productcatalog/plan/adapter/plan.go
Let's treat deleted as deleted and not return deleted phases or ratecards.
=> Exclude deleted plan contents from GET response

openmeter/billing/worker/collect/collect.go
Fix calculation of the `asOf` time used to determine pending lines to include in invoice.
=> fix(billing): asOf calculation for invoicing

deploy/charts/openmeter/values.example.yaml
=> fix(deploy): helm chart

openmeter/billing/worker/collect/collect.go
Skip invoices with no billable lines from invoice collection.
=> fix(billing): skip invoices with no billable lines

openmeter/billing/service/collectionat.go, openmeter/billing/worker/collect/collect.go
Make sure that the invoice collection `asOf` time is aligned with the `invoiceAt` attribute of the latest valid invoice line included in the newly created invoice.
=> refactor(billing): mk invoice collection asOf aligned

openmeter/app/stripe/entity/input.go
=> fix(stripe): checkout session input validation

openmeter/billing/worker/subscription/handlers.go, openmeter/billing/worker/subscription/sync.go, openmeter/billing/worker/worker.go
This helps with the user experience so that we don't have to wait for the collector to complete.
=> feat: canceled subscription should invoke invoice now

openmeter/app/stripe/adapter/stripe.go, openmeter/secret/adapter.go, openmeter/secret/adapter/secret.go, openmeter/secret/service.go, openmeter/secret/service/secret.go, test/app/stripe/secret_mock.go
Allow app secret update with ID change.
=> feat(app): secret update with id change

openmeter/billing/adapter/invoice.go, openmeter/billing/adapter/profile.go, openmeter/billing/errors.go, openmeter/billing/invoiceline.go, openmeter/billing/service/profile.go, openmeter/billing/service/service.go, openmeter/customer/errors.go
When invoice action receives unknown customer ID, let's properly return 404
When lines are failed to validate return all validation errors
When profiles endpoints get invalid profile ID return 404
If an invoice is not found return 404 with consistent error codes
=> fix: billing error reporting

openmeter/billing/service/invoiceline.go, test/billing/invoice_test.go
If a gathering invoice (even deleted) exists for a specific line let's reuse that invoice instead of generating a new one.
=> fix: reuse gathering invoices

app/common/app.go, openmeter/app/stripe/adapter/adapter.go, openmeter/app/stripe/adapter/customer.go, openmeter/app/stripe/adapter/stripe.go, openmeter/app/stripe/client/appclient.go, openmeter/app/stripe/client/client.go, openmeter/app/stripe/client/logger.go, openmeter/app/stripe/entity/app/app.go, openmeter/app/stripe/entity/app/client.go, openmeter/app/stripe/entity/app/customer.go, openmeter/app/stripe/entity/app/invoice.go, openmeter/app/stripe/service/factory.go, openmeter/billing/invoice.go, test/app/stripe/invoice_test.go, test/app/stripe/testenv.go, test/app/testenv.go
This patch makes sure that:
- We log stripe client errors on warning level
- We add the source: "stripe-go" attribute to all logs
- We add contextual information (as much as possible) for the errors for troubleshooting reasons.
=> fix: improve stripe logging

openmeter/subscription/subscriptionview.go
fixing errors of this kind:
```
subscription active to 2025-02-04 17:47:36.718396 +0000 UTC does not match spec active to 2025-02-04 17:47:36.718396 +0000 UTC
```
=> Fix Nil-ish Time Comparison

.github/workflows/ci.yaml
The action we're using is getting deprecated (with GitHub deprecating the underlying API), lets see what impact it has if we run our CI without that cache.
=> Test without nix cache

openmeter/billing/worker/subscription/phaseiterator.go, openmeter/billing/worker/subscription/phaseiterator_test.go
This logic wasn't implemented resulting in syncing errors
=> Fix one-time lines in aligned subs

openmeter/entitlement/metered/grant_owner_adapter.go
This makes sure that we see what caused the error in case it's not a not found issue.
=> fix: make sure we are propagating non not found errors

pkg/models/meter.go, pkg/models/meter_test.go
- validate if a meter with count has no value prop
- fix validation tests
=> fix(meter): validate value prop with count

openmeter/productcatalog/plan/httpdriver/mapping.go
Lets deserialize to the correct thing.
=> Fix mapping typo

api/client/javascript/src/client/schemas.ts, justfile
=> Add JS client generation to `just generate`

openmeter/watermill/driver/kafka/broker.go
=> feat: add otel scope to sarama logger

openmeter/productcatalog/plan/httpdriver/mapping.go
Let's fix this defaulting behavior as its already stated in the docs
=> Use UsagePeriod defaulting as written in docs

pkg/log/panic.go
Use OTel stacktrace label in `PanicLogger`.
=> feat: add otel stacktrace to paniclogger

app/common/runner.go, cmd/notification-service/main.go, cmd/server/main.go, cmd/sink-worker/main.go
Fix panic triggered by error matching on shutdown.
=> fix: panic on shutdown

openmeter/streaming/clickhouse/raw_events/meter_query.go, openmeter/streaming/clickhouse/raw_events/meter_query_test.go
Treat JSON path not found as null so aggregation can skip it.
=> feat(streaming): null if no value

openmeter/streaming/clickhouse/raw_events/connector.go
Fix scanning null value columns.
=> fix(streaming): raw event connector with null query

openmeter/billing/adapter/validationissue.go
Deduplicate validation issues to avoid:
`ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time (SQLSTATE 21000)`
=> fix(billing): dedupe invoice validation issues

openmeter/streaming/clickhouse/raw_events/meter_query.go
Fix count queries with raw event processor.
=> fix(streaming): raw query count

openmeter/billing/adapter/validationissue.go
=> fix(invoice): validation issue deduping

openmeter/billing/worker/advance/advance.go
Improve logging on cannot advance issues.
=> chore: cannot advance logging

openmeter/billing/worker/subscription/sync.go, openmeter/billing/worker/subscription/sync_test.go
Fixes syncing panic happening due to excluding de-facto 0 prices from line generation
=> Hotfix sync exclusion rules

openmeter/billing/worker/subscription/handlers.go
The customer's Namespace field is lost due to json serialization, so let's use the subscription's.
=> feat: cancel namespace setting

openmeter/streaming/clickhouse/materialized_view/connector.go, openmeter/streaming/clickhouse/raw_events/connector.go
Always close rows and handle rows errors
=> fix(streaming): clickhouse row close

openmeter/ent/schema/app_stripe.go, openmeter/ent/schema/feature.go, openmeter/ent/schema/productcatalog.go, tools/migrate/migrations/20250218102532_fix-unique-indexes.down.sql, tools/migrate/migrations/20250218102532_fix-unique-indexes.up.sql, tools/migrate/migrations/atlas.sum
=> fix: index fixes

openmeter/ent/db/migrate/schema.go, openmeter/ent/schema/billing.go, test/billing/invoice_test.go, tools/migrate/migrations/20250218161614_billing-profile-fix-constraint.down.sql, tools/migrate/migrations/20250218161614_billing-profile-fix-constraint.up.sql, tools/migrate/migrations/atlas.sum
Fix unique constraint to only restrict the default profile.
=> fix: regression on default billing profile promotion

Dockerfile
Refactor Dockerfile to utilize build cache layers better.
=> refactor: Dockerfile

Dockerfile, benthos-collector.Dockerfile
Refactor Dockerfiles:
* make `collector` Dockerfile aligned
* use `COPY` with `--link` whereever it makes sence
=> refactor: Dockerfiles

go.mod, go.sum, openmeter/notification/webhook/svix.go
Bump `Svix` Go library and adopt changes.
=> chore: bump Svix to v1.59.1

deploy/charts/benthos-collector/README.md, deploy/charts/benthos-collector/templates/configmap.yaml, deploy/charts/benthos-collector/templates/deployment.yaml, deploy/charts/benthos-collector/values.yaml, deploy/charts/openmeter/README.md, deploy/charts/openmeter/templates/configmap.yaml, deploy/charts/openmeter/templates/deployment.yaml, deploy/charts/openmeter/values.yaml
Add support for injecting CA certificates into pods/containers to Helm charts.
=> feat(helm): add support for injecting CA certs

openmeter/portal/httphandler/errors.go
=> fix(portal): meter not found

collector/benthos/input/run_ai.go, collector/benthos/input/runai/metrics.go, collector/benthos/input/runai/pods.go, collector/benthos/input/runai/token.go, collector/benthos/input/runai/workloads.go
- Support more than 10 metric types (multiple metric request)
- Run.ai pod metrics
- Fix jwt token expiration check
=> feat(collector): run.ai pod metrics and token expiration check

openmeter/entitlement/adapter/entitlement.go, openmeter/entitlement/entitlement.go, openmeter/entitlement/metered/grant_owner_adapter.go
Show correct period value if there wasnt a manual reset
=> Leep current UsagePeriod up to date for programmatic resets

openmeter/subscription/timing.go
Enable immediate canceling for aligned subscriptions
=> Enable immediate cancel for aligned subs

openmeter/credit/helper.go, openmeter/entitlement/metered/balance.go
1. Truncate inputs to meter precision so non-truncated queries no longer return 400 errors: from & to are truncated to meter precision. If `to` is not truncated it is rounded up to next minute (so latest events are included)
2. Add intermediary wrapper to allow 0 length periods in meter queries
- Follow-up PR will rewrite most of history management and the code affected here. The aim of this PR is to fix our current prod issues until then too.
=> Entitlement History Fix

openmeter/billing/service/lineservice/service.go
This is a temporary measure, it will cause some performance regressions. The cache will be added back as part of a bigger refactor that optimizes calls and pre-fetches features and meters.
=> fix: remove feature cache temporarily

deploy/charts/benthos-collector/templates/statefulset.yaml
Extend `collector` pod environment variables with metadat information.
=> feat: add meta to collector pod env

openmeter/entitlement/balanceworker/entitlementhandler.go, openmeter/entitlement/balanceworker/ingesthandler.go, openmeter/entitlement/balanceworker/worker.go, openmeter/entitlement/metered/events.go, openmeter/entitlement/metered/reset.go, openmeter/sink/flushhandler/ingestnotification/events/events.go, openmeter/sink/flushhandler/ingestnotification/handler.go
The high watermark cache was not operational due to always recalculating the same value.
=> fix: high watermark cache

app/common/openmeter_balanceworker.go, cmd/balance-worker/wire_gen.go
=> Use a single method in all setup to avoid wire collisions

openmeter/app/stripe/httpdriver/checkout_session.go
As per the API spec we are returning 201
=> chore: fix checkout session status code

openmeter/productcatalog/subscription/http/errors.go, openmeter/productcatalog/subscription/service/plan.go, openmeter/productcatalog/subscription/testutils/adapter.go, openmeter/subscription/errors.go, openmeter/subscription/plan.go, openmeter/subscription/repo/subscriptionitemrepo.go, openmeter/subscription/repo/subscriptionphaserepo.go, openmeter/subscription/repo/subscriptionrepo.go, openmeter/subscription/service/workflowservice_test.go, openmeter/subscription/state.go
=> fix(subscription): error handling

openmeter/app/stripe/client/checkout.go, openmeter/app/stripe/entity/input.go, openmeter/app/stripe/httpdriver/checkout_session.go
- remove returnUrl check because it can be optional and required based on Stripe settings
- make customer lookup or create logic more robust
=> fix(stripe): create checkout session customer

openmeter/billing/worker/subscription/handlers.go, openmeter/billing/worker/subscription/sync_test.go, openmeter/billing/worker/worker.go
So that we are no honoring the collection period (which either ways would only exist to allow for late(er) events).
=> feat: invoice in advance flat fees on subs creation

openmeter/billing/invoiceline.go, test/billing/invoice_test.go
We should allow zero prices to signify that something is free, but we still want to show that on the invoice.
If something should not be invoiced, then it should not have prices set.
=> fix: allow zero prices

openmeter/app/stripe/client/invoice_line.go, openmeter/app/stripe/entity/app/invoice.go, test/app/stripe/appstripe.go, test/app/stripe/fixture.go, test/app/stripe/invoice_test.go
Add support for creating stripe invoices without line items. This can be used to signify that the user does not have any charges pending.
=> fix: app stripe support empty invoices

app/common/billing.go, app/common/subscription.go, cmd/billing-worker/wire_gen.go, cmd/jobs/internal/wire_gen.go, cmd/server/wire_gen.go, openmeter/billing/validators/customer/customer.go, openmeter/server/server_test.go, openmeter/subscription/service.go, openmeter/subscription/service/service.go, openmeter/subscription/testutils/mock.go
=> fix: gathering invoice deletion from sync

openmeter/billing/worker/subscription/sync.go
=> chore: do not sync subscriptions without billble items

app/common/customer.go, openmeter/customer/adapter/customer.go, openmeter/entitlement/validators/customer/validator.go, test/customer/customer.go, test/customer/testenv.go
=> Validate customer relations before delete and update

flake.lock
=> chore: bump nix env

openmeter/app/stripe/client/invoice.go
We should only set due date if the invoice is in send invoice mode.
=> fix: stripe invoice setting

openmeter/productcatalog/plan/httpdriver/plan.go
Fix missing error mapping for validation errors.
=> fix: map validation error for plan create request

openmeter/billing/worker/subscription/sync.go, openmeter/billing/worker/subscription/sync_test.go
Fix the prorating behavior of subscription sync
=> feat: test prorating

openmeter/app/httpdriver/customer.go
Fix resolving billing application id from customers billing profile.
=> fix(app): resolving app id from customer billing profile

openmeter/billing/worker/subscription/sync.go
=> fix: decrease subs sync noise

openmeter/ent/db/migrate/schema.go, openmeter/ent/db/mutation.go, openmeter/ent/db/runtime.go, openmeter/ent/db/setorclear.go, openmeter/ent/db/usagereset.go, openmeter/ent/db/usagereset/usagereset.go, openmeter/ent/db/usagereset/where.go, openmeter/ent/db/usagereset_create.go, openmeter/ent/db/usagereset_update.go, openmeter/ent/schema/usage_reset.go, pkg/datetime/duration.go, tools/migrate/entitlement_test.go, tools/migrate/migrate.go, tools/migrate/migrations/20250807075408_usageperiod-duration-calculations.down.sql, tools/migrate/migrations/20250807075408_usageperiod-duration-calculations.up.sql, tools/migrate/migrations/atlas.sum, tools/migrate/testdata/sqlcgen/20250703081943/db/models.go, tools/migrate/testdata/sqlcgen/20250703081943/db/queries.sql.go, tools/migrate/testdata/sqlcgen/20250703081943/sqlc/queries.sql
- Generates `UsageResets` with normalized values to backfill in preparation for new algorithm
- Mark `BillingInvoiceLines` with annotations so they are ignored &/|| reanchor
=> feat(entitlement): write migration to persist normalized values

openmeter/subject/service/service.go
Remove creation of new database transaction for immutable operations like _get, list_ in Subject service.
=> fix: rm new tx for immutable operations in subject service
