openmeterio/openmeter

examples/export-stripe-go/README.md
examples/export-stripe-go/main.go
examples/export-stripe-go/server.go
examples/export-stripe-go/setup.go

Improve Stripe export example.
- setup Stripe entities via code to reduce steps
- remove unnecessary webhook setup
- round down period dates

refactor(example): stripe export

---

.github/workflows/ci.yaml

Dependabot PRs have been failing due to FOSSA not being able to push reports. (The reason behind that is the secret is not available to external PRs)
Let's disable FOSSA on PRs for now.
Fixes #17

ci: disable fossa scan on pull-requests for now

---

examples/export-stripe-node/.gitignore
examples/export-stripe-node/README.md
examples/export-stripe-node/app.ts
examples/export-stripe-node/package-lock.json
examples/export-stripe-node/package.json
examples/export-stripe-node/setup.ts
examples/ingest-openai-node/.gitignore
examples/ingest-openai-node/.prettierrc.json
examples/ingest-openai-node/README.md
examples/ingest-openai-node/app.ts
examples/ingest-openai-node/openapi.d.ts
examples/ingest-openai-node/package-lock.json
examples/ingest-openai-node/package.json
examples/ingest-openai-node/tsconfig.json
quickstart/config.yaml
quickstart/docker-compose.yaml

- add `depends_on` to quickstart docker-compose (extend [doesn't inherit it](https://docs.docker.com/compose/extends/#extending-services))
- add a new metric to quickstart to track AI token usage
- change node-stripe example to be AI focused
- fix content type for node stripe example
- add `REPORT_ALL` to node stripe example to make it easy to report current usage

feat(example): ai tokens

---

api/api.gen.go
api/openapi.yml
internal/models/meter.go
internal/models/meter_test.go
internal/server/router/router.go

When `windowSize` query parameter is not defined, the total aggregate will be returned for the specified period for each subject and group.
**BREAKING CHANGES**
- Changes the behavior of the `windowSize` query param from being the default of the meter's window size.
- Changed the response field `values` to `data`
Possible improvements:
- specify `groupBy` query parameter for groups to be ignored or selected
TODO:
- update examples

feat(api): add total aggregate

---

quickstart/docker-compose.yaml

Always pull quickstart openmeter image and restart on failure.

fix(quickstart): docker compose always pull

---

internal/ingest/kafkaingest/schema.go

We didn't try to parse incoming CloudEvents `data` as JSON before. 
Even if it was JSON, whitespace, and new lines made into the Kafka message.
This PR tries to parse data as JSON before serializing.

fix(ingest): parse data

---

config.go
docker-compose.yaml
go.mod
go.sum
internal/ingest/dedupe.go
internal/ingest/httpingest/httpingest.go
internal/ingest/memorydedupe/collector.go
internal/ingest/memorydedupe/collector_test.go
internal/ingest/redisdedupe/collector.go
main.go
quickstart/docker-compose.yaml

Dedupe in API via Redis.
Deduping in the API can't guarantee consistency due to the parallel ingestion of events.
Currently, the only consistent deduplication is provided by the ksqlDB Processor.

feat(dedupe): add redis dedupe

---

deploy/charts/openmeter/Chart.lock

Updates the Helm chart's `Chart.lock` via `helm dependency update`. This currently blocks ArgoCD from deploying due to the out of date `Chart.lock` file.

chore: update helm Chart.lock digest

---

internal/server/router/router.go

Reverting https://github.com/openmeterio/openmeter/pull/162 partially.
The Chi framework already logs `elapsed_time` in debug mode.

feat(router): remove execution time logging

---

config.go
go.mod
go.sum
main.go

This PR adds basic otel trace support for incoming requests. Integration for downstream requests (kafka, clickhouse) will be added in subsequent PRs.

Basic otel trace support

---

config.go

fix(dedupe): config default typo

---

internal/meter/inmemory.go
internal/meter/meter.go
internal/streaming/clickhouse_connector/connector.go
main.go

This PR introduces a repository interface for meters. It allows us to get meter info during meter queries where appropriate.
The relevant API parameters will be cleared out in a followup PR.

feat: add meter repository

---

internal/streaming/clickhouse_connector/query.go
internal/streaming/clickhouse_connector/query_test.go

Use absolute path to filter on events table's `type` at materialized view creation to avoid shadowing if the MV has a `type` column due to a group by.

fix(processor): clickhouse materialized view type shadow

---

api/api.gen.go
api/client/go/client.gen.go
api/client/node/README.md
api/client/node/clients/event.ts
api/client/node/test/api.test.ts
api/openapi.yaml
internal/server/router/router.go
internal/server/server_test.go
internal/streaming/clickhouse_connector/connector.go
internal/streaming/connector.go

Rename raw events query to list.
Not a breaking change as we didn't release since https://github.com/openmeterio/openmeter/pull/296

feat(api): rename query events to list

---

config/config.go
config/config_test.go
internal/meter/inmemory.go
internal/meter/meter.go
pkg/models/meter.go

Pre-work to adapt meter repository in Sink Worker:
https://github.com/openmeterio/openmeter/pull/320
Sink worker needs to know about all namespaces to subscribe to Kafka Topics and all meters to validate events against them.

feat(meter): add list all meters and add namespace to meter

---

openmeter/ingest/dedupe.go

It was accidentally removed in https://github.com/openmeterio/openmeter/pull/320

fix(openmeter): export dedupe

---

api/api.gen.go
api/client/go/client.gen.go
api/openapi.yaml

The generated client has to use the StatusProblem struct instead of the Problem interface to be able to unmarshal the body:
```go
var dest UnexpectedProblemResponse
if err := json.Unmarshal(bodyBytes, &dest); err != nil {
return nil, err
}
response.ApplicationproblemJSONDefault = &dest
```

fix(api): use struct instead of interface for response problem type

---

internal/server/router/router.go

If I want to query in my browser (Google Chrome), the mime package returns an error:
> `mime: unexpected content after media subtype`
This PR defaults to JSON when it happens instead of erroring out request.

fix(router): default to json with invalid mime

---

internal/server/router/router.go
internal/server/server_test.go
internal/streaming/clickhouse_connector/connector.go
internal/streaming/clickhouse_connector/query.go
internal/streaming/clickhouse_connector/query_test.go
internal/streaming/connector.go

Adding optional `from` and `to` filters to meter subject list.

feat(connector): meter subjects from to

---

api/api.gen.go
api/client/go/client.gen.go
api/openapi.yaml
internal/server/router/router.go
internal/streaming/clickhouse_connector/connector.go
internal/streaming/clickhouse_connector/query.go
internal/streaming/clickhouse_connector/query_test.go
internal/streaming/connector.go

- Remove `aggregation` input from the query API. Aggregation of aggregation doesn't always applicable.
- Move query params to OpenAPI components for reusability.
- Add `QueryMeterWithMeter` for query route reusability
BREAKING CHANGE:
- Remove `aggregation` query string parameter from `/api/v1/meters/:id/query`

feat(api)!: remove aggregation from query api

---

internal/ingest/httpingest/httpingest.go
internal/server/router/router.go
internal/streaming/connector.go
internal/streaming/query_params.go
internal/streaming/query_params_test.go

- Convert non UTC API inputs to UTC
- Fix query params validator to allow querying fine-grained window size meters on coarser window sizes.

fix(streaming): query params validator and timezones

---

pkg/models/meter.go

Do not allow `events` meter slug name.

fix(meters): restricted slug name: events

---

internal/sink/sink.go

Sink shouldn't control the `consumer` lifecycle.

fix(sink): do not close consumer

---

examples/export-stripe-go/report.go
internal/server/router/router.go
internal/server/server_test.go
internal/sink/namespaces.go
internal/sink/namespaces_test.go
internal/streaming/clickhouse_connector/connector.go
internal/streaming/connector.go
openmeter/streaming/connector.go
pkg/models/meter.go

- allow ingesting events without group by
- return null in meter query if group by is empty
- cleanup unnecessary intermediate types
Missing `method` group-by.
```sh
curl -X POST http://localhost:8888/api/v1/events \
-H "Expect:" \
-H 'Content-Type: application/cloudevents+json' \
--data-raw '
{
"specversion" : "1.0",
"type": "api-calls",
"id": "00001",
"time": "2023-01-01T00:00:00.001Z",
"source": "service-0",
"subject": "customer-1",
"data": {
"duration_ms": "1",
"path": "/hello"
}
}
```
Both `path` and `method` group-bys are present.
```sh
curl -X POST http://localhost:8888/api/v1/events \                      
-H "Expect:" \
-H 'Content-Type: application/cloudevents+json' \
--data-raw '
{
"specversion" : "1.0",
"type": "api-calls",
"id": "00002",
"time": "2023-01-01T00:00:00.001Z", …
```

feat(ingest): allow optional group by

---

internal/server/router/router.go

```
GET http://127.0.0.1:8888/api/v1/meters/m1/query?from=2023-01-01T01:00:00Z&to=2023-01-01T09:00:00Z
```
Before:
```json
{
"from": "2023-01-01T01:00:00Z",
"to": "2023-01-01T09:00:00Z",
"data": [
{
"value": 2,
"windowStart": "2023-01-01T01:00:00Z",
"windowEnd": "2023-01-01T01:02:00Z",
"subject": null,
"groupBy": {
}
}
]
}
```
After:
```json
{
"from": "2023-01-01T01:00:00Z",
"to": "2023-01-01T09:00:00Z",
"data": [
{
"value": 2,
"windowStart": "2023-01-01T01:00:00Z",
"windowEnd": "2023-01-01T09:00:00Z",
"subject": null,
"groupBy": {
}
}
]
}
```

If total value is queried for a period, replace the window start and end with the period for each row

---

go.mod
go.sum

Reverts openmeterio/openmeter#452
```
go generate ./...
../.devenv/state/go/pkg/mod/github.com/deepmap/oapi-codegen/v2@v2.0.0/pkg/codegen/codegen.go:231:53: cannot use spec.Components.Responses (variable of type openapi3.ResponseBodies) as openapi3.Responses value in argument to GenerateResponseDefinitions
../.devenv/state/go/pkg/mod/github.com/deepmap/oapi-codegen/v2@v2.0.0/pkg/codegen/codegen.go:403:54: cannot use swagger.Components.Responses (variable of type openapi3.ResponseBodies) as openapi3.Responses value in argument to GenerateTypesForResponses
../.devenv/state/go/pkg/mod/github.com/deepmap/oapi-codegen/v2@v2.0.0/pkg/codegen/codegen.go:564:29: invalid operation: cannot index responses (variable of type openapi3.Responses) …
```

Revert "chore(deps): bump github.com/getkin/kin-openapi from 0.120.0 to 0.121.0"

---

.dockerignore
.github/workflows/artifacts.yaml

Container image builds keep failing due to GHA cache errors.
While this may cause longer build times in the short run, it's still better than having to rerun builds all the time.
https://github.com/moby/buildkit/issues/2492

ci: ignore cache errors

---

cmd/server/main.go
docker-compose.yaml

- Fix running Kafka producer async error listener.
- We manage Kafka topics manually so set auto create to false

fix(server): kafka run group

---

.github/workflows/artifacts.yaml

A recent change in GHA causes image builds to break.
The culprit is the vulnerability scan artifact upload. Since we don't actually need it as a build artifact (it gets uploaded to the GH security tab), this PR turns that off for now.

Do not upload trivy results

---

pkg/models/meter.go

From the Go specification [^1]:
> "3. If the map is nil, the number of iterations is 0."
`len` returns 0 if the map is nil [^2]. Therefore, checking `len(v) != 0` around a loop is unnecessary.
[^1]: https://go.dev/ref/spec#For_range
[^2]: https://pkg.go.dev/builtin#len

refactor(models/meter): remove redundant len check in `Validate`

---

api/api.gen.go
api/client/go/client.gen.go
api/client/node/README.md
api/client/node/clients/subject.ts
api/client/node/index.ts
api/client/node/schemas/openapi.ts
api/client/node/test/agent.ts
api/client/node/test/api.test.ts
api/openapi.yaml

- Replace single subject upsert with an array of subjects. (breaking)
- Fix naming in Node SDK `openmeter.subject` => `openmeter.subjects` (breaking)

feat(subject): batch upsert

---

config.example.yaml
examples/ingest-logs/README.md
quickstart/README.md
quickstart/config.yaml
quickstart/docker-compose.yaml
quickstart/ingest.sh
quickstart/verify.sh

Update quickstart and example meters to follow common meters:
https://openmeter.io/docs/getting-started/meter-examples

feat(quickstart): use unified meters

---

api/client/go/README.md

Fix go client version for `go get` install instruction.

docs(client): add version to go client

---

api/client/python/config.yaml
api/client/python/poetry.lock
api/client/python/pyproject.toml
api/client/python/src/openmeter/_client.py
api/client/python/src/openmeter/_operations/_operations.py
api/client/python/src/openmeter/aio/_client.py
api/client/python/src/openmeter/aio/_operations/_operations.py

Fixes generation. The `apiKey` securityScheme type is a catch all for AzureKey.
https://github.com/Azure/autorest/blob/main/packages/extensions/modelerfour/src/modeler/security-processor.ts#L195
```
fatal   | Error: AzureKey security scheme should be of in 'header' but was 'cookie'
fatal   | Process() cancelled due to failure 
error   |   Error: Plugin modelerfour reported failure.
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at 
```

fix(api): python generator

---

cmd/sink-worker/main.go
internal/sink/sink.go

* use `context.Context` for fetching `namespaces`
* make OTel initialization errors more descriptive

refactor(sink-worker): use contex.Context for fetching namespaces

---

cmd/server/main.go
collector/benthos/internal/message/transaction.go
collector/benthos/internal/shutdown/signaler.go
internal/ingest/kafkaingest/collector.go

- Add a new metric to count ingested events.
- Initialize OTel the same way as in sink-worker

feat(backend): add ingest event counter metric

---

config/ingest.go

Allow setting `broker.address.family` config parameter for Kafka client(s).

feat: mk broker.address.family configurable

---

cmd/server/main.go
cmd/sink-worker/main.go

Replace `environment` tag with the conventional `deployment.environment`.
For example:
https://docs.datadoghq.com/opentelemetry/schema_semantics/semantic_mapping/#unified-service-tagging

feat(otel): use conventional environment tag

---

cmd/sink-worker/main.go
config/config_test.go
config/ingest.go
config/sink.go

Make some Kafka client related parameters configurable:
* allow setting client ID for Kafka client which could help debugging
* allow using TCP keep-alive to avoid closing idle connections by the Kafka broker
* increase session timeout in order to avoid freqent partition rebalance due to missed heartbeats sent by the Kafka consumer
* allow changing the metadata cache invalidation timeout which could help with detecting changes in Kafka cluster faster in case lower value is used
This change is an attempt to allow tweaking Kafka client parameters to reduce the number of errors generated by the `sink-worker` during processing data from  Kafka cluster.

feat(sink-worker): make some Kafka parameters configurable

---

e2e/e2e_test.go

Tests running on GHA are _really_ slow compared to ... well, anything.
Until we have better runners, this is a temporary measure to avoid flaky e2e tests.

test(e2e): increase eventual timeout

---

go.mod
go.sum

Downgrades `kin-openapi` for `oapi-codegen` compatibility. See [this issue](https://github.com/deepmap/oapi-codegen/issues/1533)
Fixes #(issue)

fix(deps): roll back kin-openapi for oapi-codegen compatibility

---

internal/sink/sink.go

Prevent invoking `sink.Close()` from stopping `sink-worker` while `flush` operation is being performed in order to avoid events in buffer being processed twice due to inconsistent state where events data is already stored in storage (Clickhouse), but not in Kafka and/or Redis.
Use mutex to make `sink.Close()` to detect if `flush` operation is undergoing and delay shutdown until it is finished.
This change does not solve the issue where error(s) occurs during the `flush` operation which might result in data being inconsistent state.
Additional safeguards are going to be added to the `sink-worker` in followup PRs.

fix(sink-worker): prevent closing during flush operation

---

.editorconfig

Add *golang* specific configuration to `.editorconfig`.

chore: add go config to editorconfig

---

config.example.yaml
config/config_test.go
config/ingest.go
config/ingest_test.go
config/testdata/complete.yaml
pkg/kafka/config.go
pkg/kafka/config_test.go

Introduce a set of configuration parameters to allow finetuning Kafka client.
The `ingest.kafka.brokerAddressFamily` config parameter defines which IP address family should be used for network communication with Kafka brokers.
The `ingest.kafka.topicMetadataRefreshInterval` config parameter defines how frequesntly the Kafka client needs to fetch metadata from Kafka cluster.
The `ingest.kafka.socketKeepAliveEnalbed` config parameter controlls whether TCP socket keep-alive is used or not for connections to Kafka brokers.
I have introduced custom types (`BrokerAddressFamily` and `TimeDurationMilliseconds`) for Kafka configuration parameters in order to:
* improve configuration validation by catching invalid configuration early on
* avoid runtime configuration errors (which may or may not be …

feat: add Kafka client configs

---

cmd/sink-worker/main.go
internal/sink/sink.go

Refactor `sink-worker` adding tiny improvements/fixes:
* proper `context.Context` propagation
* properly close Kafka consumer on exit
* set exit code on error
* remove unnecessary signal handling in `sink.Sink`

refactor(sink-worker): add improvements

---

internal/productcatalog/feature_connector.go
internal/productcatalog/postgresadapter/feature.go

Add `MeterSlug` to `productcatalog.ListFeaturesParams` to allow filtering _features_ based on _meter slug_.

feat(api): allow filtering features by meterslug

---

cmd/server/main.go
internal/credit/balance_connector.go
internal/credit/engine.go
internal/credit/engine_test.go
internal/credit/owner_connector.go
internal/entitlement/connector.go
internal/entitlement/metered/balance.go
internal/entitlement/metered/balance_test.go
internal/entitlement/metered/grant_owner_adapter.go
openmeter/entitlement/adapters.go

The entitlement engine will use the meter's window resultion instead of defaulting to minute.

feat: add support for 1d meters

---

internal/entitlement/entitlement.go
internal/entitlement/httpdriver/entitlement.go
internal/entitlement/httpdriver/parser.go
internal/entitlement/postgresadapter/ent/db/entitlement.go
internal/entitlement/postgresadapter/ent/db/entitlement_create.go
internal/entitlement/postgresadapter/ent/db/entitlement_update.go
internal/entitlement/postgresadapter/ent/db/migrate/schema.go
internal/entitlement/postgresadapter/ent/db/mutation.go
internal/entitlement/postgresadapter/ent/schema/entitlement.go
internal/entitlement/postgresadapter/entitlement.go
internal/entitlement/repository.go
internal/entitlement/static/connector.go
internal/entitlement/static/entitlement.go

Store config parameter of features as byte slice and avoid unmarshaling its content as we do not to process it yet.

refactor: store feature config field as byte slice

---

internal/entitlement/entitlement.go
internal/entitlement/httpdriver/entitlement.go
internal/entitlement/httpdriver/parser.go
internal/entitlement/postgresadapter/ent/db/entitlement.go
internal/entitlement/postgresadapter/ent/db/entitlement_create.go
internal/entitlement/postgresadapter/ent/db/entitlement_update.go
internal/entitlement/postgresadapter/ent/db/migrate/schema.go
internal/entitlement/postgresadapter/ent/db/mutation.go
internal/entitlement/postgresadapter/ent/schema/entitlement.go
internal/entitlement/postgresadapter/entitlement.go
internal/entitlement/repository.go
internal/entitlement/static/connector.go
internal/entitlement/static/entitlement.go

Reverts openmeterio/openmeter#1100
Unfortunately if the config is set to any valid JSON on the entitlements table, then the repo [here ](https://github.com/openmeterio/openmeter/commit/5544239c86dff91158cb245a32f1f90a1bdc2282) returns a parse error. Reverting the change for further investigation (we should just create a TC for this, as this might be a limitation of ENT itself).
cc @chrisgacsal

Revert "refactor: store feature config field as byte slice"

---

internal/sink/sink.go

- Removes a redundant error check that was previously removed in #880 but was reverted.

fix: remove redundant error check

---

internal/entitlement/metered/grant_owner_adapter.go

The default meter query params should not have a windowsize.
Fixes #(issue)

fix: engine cannot query windowed data

---

internal/entitlement/metered/balance.go

When fetching metered entitlement value, always fetch for the end of the current minute
Fixes #(issue)

fix: query usage for same period as balance is queried for

---

internal/credit/balance_connector.go
internal/credit/owner_connector.go
internal/entitlement/metered/grant_owner_adapter.go

Due to an oversight in the calculation logic, all metered usage were calculated towards entitlements. This patch ensures that we only use the specified subject's data.

fix: meters weren't filtered by subject

---

config/config_test.go
config/ingest.go
config/ingest_test.go

This allows us to reuse the Kafka configuration object in other parts of the system/other configuration files.
The mapstructure tag is required so that viper merges the two objects as expected.

refactor: split ingest and kafka specific config

---

internal/entitlement/entitlement.go
internal/entitlement/httpdriver/entitlement.go
internal/entitlement/httpdriver/parser.go
internal/entitlement/postgresadapter/ent/db/entitlement.go
internal/entitlement/postgresadapter/ent/db/entitlement_create.go
internal/entitlement/postgresadapter/ent/db/entitlement_update.go
internal/entitlement/postgresadapter/ent/db/migrate/schema.go
internal/entitlement/postgresadapter/ent/db/mutation.go
internal/entitlement/postgresadapter/ent/schema/entitlement.go
internal/entitlement/postgresadapter/entitlement.go
internal/entitlement/repository.go
internal/entitlement/static/connector.go
internal/entitlement/static/entitlement.go

Fix `config` field validation for `static` entitlements to allow any valid JSON string to be provided.
This is a revert of https://github.com/openmeterio/openmeter/pull/1114 as the issue triggered the first revert turned out to be unrelated to this change.

fix: config validation for static entitlements

---

internal/credit/engine.go
internal/credit/engine_test.go

Returned values for the entitlement history API are a lot more readable when they share the same timezone.
Fixes #(issue)

Use UTC in internal History APIs

---

cmd/server/main.go
config/dedupe.go
internal/dedupe/dedupe.go
internal/dedupe/memorydedupe/memorydedupe.go
internal/dedupe/redisdedupe/redisdedupe.go
internal/sink/sink.go

Make sure that resources used by `dedupe.Deduplicator` implementations are properly cleaned up on exit. Interface is extended with `Close()` method which allows proper cleanup of underlying resources used by implementations.

fix: dedup cleanup

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
.github/workflows/snapshot.yaml

Workaround Dagger Cloud not properly detecting Git metadata.

ci: add back git checkout step for Dagger

---

flake.lock

The local nix environment has been broken for a while with some dev environments due to a version mismatch between go, delve, etc... in the nix flake, and the tooling installed by VSCode
IMO In the future we should crossreference with all used local dev envs before
- updating go toolchain version
- updating a flake.lock
Might be nice to introduce some defined test for these cases
```
sudo rm -rf openmeter/.devenv/
sudo rm -rf openmeter/.direnv/
direnv reload
```
- This PR will have a follow-up after the release for the downstream dependencies

Fix local Nix setup with VSCode

---

cmd/sink-worker/main.go
config.example.yaml
config/config_test.go
config/ingest.go
config/ingest_test.go
config/testdata/complete.yaml
internal/ingest/kafkaingest/collector.go
pkg/kafka/config.go

Allow setting debug context for Kafka client configuration in order to get more detailed logging emitted by the `librdkafka`.
See: https://github.com/confluentinc/librdkafka/blob/master/INTRODUCTION.md#debug-contexts
This change allows us to have a better insights how Kafka clients interact with brokers and helps with spotting potentional issues which are not (properly) surfaced.

feat(sink-worker): enable kafka client logging

---

config/config.go

Why
Running OpenMeter without any meter configured makes no sense.
This is especially important as our Kubernetes Helm chart comes with [no meters](https://github.com/openmeterio/openmeter/blob/main/deploy/charts/openmeter/templates/configmap.yaml).
What
Return error when no meter is configured to indicate user that action is required.

feat(config): validate meters config length

---

.vscode/settings.json
api/api.gen.go
api/client/go/client.gen.go
api/client/node/clients/subject.ts
api/client/node/schemas/openapi.ts
api/client/python/src/openmeter/_operations/_operations.py
api/client/python/src/openmeter/aio/_operations/_operations.py
api/client/web/src/client/openapi.ts
api/openapi.yaml
internal/entitlement/httpdriver/metered.go
internal/entitlement/metered/connector.go
internal/entitlement/metered/entitlement_grant.go
internal/server/router/entitlement.go

Allow usage granting and grant listing by feature key
Fixes OM-812
The original intent was to allow granting based on featureKey (we have a constraint of a single entitlement per subject per featureKey), but for the API to be resolvable / deterministic, the entire `/grants` subpath had to be moved to work with featureKey

Allow usage granting and grant listing by feature key OM-812

---

api/api.gen.go
api/client/go/client.gen.go
api/openapi.yaml

Update Notification API to return metadata of the resources in responses
instead of their identifiers as:
* there are resources (e.g. `feature`) which may have two unique
identifiers wher one generated by the system (`id`) and the other provided by
the user (`key`)
* this response structure allows us to add support for resource
*expand* feature where users can request the API to expand certain
fields in the response like returning the full resources instead of
their limited representaion (including only their metadata like
unique identifiers)
Additionally rename Notification API related API resources using `Generic` prefix to `Common`.

refactor(api): return meta object instead of id

---

api/api.gen.go
api/client/go/client.gen.go
api/openapi.yaml

Add notification event type playload to the OepnAPI specification. Currently only payload for notifications with `entitlements.balance.threshold` type is supported.

refactor(api): notification event payload

---

cmd/server/main.go
internal/watermill/driver/kafka/publisher.go
openmeter/credit/events.go
openmeter/entitlement/events.go
openmeter/entitlement/metered/events.go
openmeter/event/publisher/publisher.go
openmeter/watermill/driver/kafka/driver.go
openmeter/watermill/driver/noop/driver.go

Expose the event subsystem to be used in the cloud instance.
This patch also fixes:
- invalid package name for kafka watermill package
- closing of the admin client after use

chore: expose event subsystem for the cloud deployment

---

internal/entitlement/postgresadapter/entitlement.go
internal/entitlement/repository.go
internal/productcatalog/feature_connector.go
internal/productcatalog/postgresadapter/feature.go

Contrary to OpenMeter, OpenMeter Cloud has hard delete, which requires additional checks to be in place before executing those deletes. 
There's no trivial way to link the cloud only ent schema with the OpenMeter ent schema so we can't rely on DB constraints, these checks have to happen manually.

Expose methods for checking if a meter has entitlement entities associated

---

.vscode/launch.json
cmd/sink-worker/main.go
config.example.yaml
config/config_test.go
config/events.go
internal/event/spec/resourcepath.go
internal/sink/flushhandler/handler.go
internal/sink/flushhandler/ingestnotification/events.go
internal/sink/flushhandler/ingestnotification/handler.go
internal/sink/flushhandler/meters.go
internal/sink/flushhandler/mux.go
internal/sink/flushhandler/types.go
internal/sink/sink.go
openmeter/sink/flushhandler/flushhandler.go
openmeter/sink/flushhandler/ingestnotification/ingestnotification.go
openmeter/sink/sink.go

This patch ensures that we can create events when we have successfully ingested a new event into our system. The event payload is the following:
```
{
"id": "9f78f699-2b60-45c5-b820-50be6841afe0",
"source": "//openmeter.io/namespace/default/event/9f78f699-2b60-45c5-b820-50be6841afe0",
"type": "openmeter.ingest.v1.ingestion",
"subject": "//openmeter.io/namespace/default/subjectKey/customer-1",
"datacontenttype": "application/json",
"time": "2024-07-26T09:53:56.108182Z",
"data": {
"namespace": {
"id": "default"
},
"subjectKey": "customer-1",
"meterSlugs": [
"api_requests_total"
]
}
}
```
As part of the work an improved version of the flushhandler is added, so that we can hook in usage reporting in the cloud solution.

feat: ingest events

---

cmd/balance-worker/main.go
cmd/server/main.go
cmd/sink-worker/main.go
config/aggregation.go
internal/entitlement/balanceworker/worker.go
internal/registry/entitlement.go

This patch ensures that entitlements are initialized for the balance workers.
This patch moves the clickhouse initialization's options part to the config package, as we have some magic constants there that should become config options.
It moves the entitlements initialization to a registry package, as at most of the places we are initializing credit, entitlements, and product catalog together: that's just a boilerplate we should not copy.
This is based on feedback from https://github.com/openmeterio/openmeter/pull/1274

feat: add entitlements initialization - v2

---

internal/credit/events.go
internal/entitlement/events.go
internal/entitlement/metered/events.go
internal/entitlement/metered/reset.go
internal/entitlement/snapshot/event.go
internal/event/spec/event_type.go
internal/event/spec/parser.go
internal/event/spec/parser_test.go
internal/sink/flushhandler/ingestnotification/events.go
internal/sink/flushhandler/ingestnotification/handler.go
openmeter/credit/events.go
openmeter/entitlement/events.go
openmeter/entitlement/metered/events.go
openmeter/sink/flushhandler/ingestnotification/ingestnotification.go

Changes:
- append io. to type names example io.openmeter.entitlement.v1.entitlement.created
- unify event naming (use entity.action scheme)
- remove spec version from type meta as that's 1.0 for all cloudevents (that's the cloudevent's version number)
- do not export eventName as we are getting the Type() from the object

refactor: event naming consistency

---

cmd/balance-worker/main.go
cmd/notification-service/main.go
openmeter/entitlement/balanceworker/worker.go
openmeter/event/publisher/publisher.go
openmeter/notification/consumer/consumer.go
openmeter/registry/entitlement.go

Fixes:
- Expose required objects
- Fix service name constants

chore: expose balance and notification types

---

examples/ingest-logs/README.md
examples/ingest-logs/docker-compose.yaml
examples/ingest-logs/vector.yaml
quickstart/config.yaml

Fix Vector.dev example:
- update vector image
- update API ingestion endpoint
- use uuid for event id
- add new meter to quickstart
- change event type to `request`
- change `path` to `route`
https://stackoverflow.com/questions/78825882/issues-with-sending-data-to-openmeter-from-vector-dev-using-http-sink
[Rishabh](https://stackoverflow.com/users/10403713/rishabh) Thank you for raising the issue! We'd like to invite you to our discord: https://discord.gg/nYH3ZQ3Xzq

fix(examples): update vector example

---

cmd/balance-worker/main.go
cmd/notification-service/main.go
cmd/server/main.go
cmd/sink-worker/main.go
internal/watermill/driver/kafka/marshaler.go
internal/watermill/driver/kafka/metrics/README.md
internal/watermill/driver/kafka/metrics/adapter.go
internal/watermill/driver/kafka/publisher.go
internal/watermill/driver/kafka/topic_provision.go
openmeter/watermill/driver/kafka/driver.go

This patch uses the sarama lib for internal message publishing. This patch also adds support for exposing the sarama metrics using the metrics bridge.
Sarama (any most probably other projects) rely on the [http://github.com/rcrowley/go-metrics](go-metrics) package, numerous connectors exist
for the package, however there seem to be no opentelemetry one.
Given the package only supports periodic scraping, it's better to wrap the metric types of go-metrics so that we can send the raw events to OpenTelemetry. The existing event interface of go-metrics is quite limited compared to OpenTelemetry esp considering the usage in Sarama lib, so right now:
- Context is context.Background() for OpenTelemetry calls
- Errors for metric registration is only logged
Example metrics:
``` …
```

feat: use sarama lib for internal message publishing

---

internal/entitlement/balanceworker/entitlementhandler.go
internal/entitlement/snapshot/event.go
openmeter/entitlement/snapshot/events.go

Static entitlements doesn't have current period set, so let's not mandate that.
This patch also renames balance to value, as the previous naming was misleading.

fix: relax entitlement snapshot event validation

---

e2e/e2e_test.go
internal/testutils/async.go

It's not clear why ingest takes so long in CI, 10 seconds is already way too long, especially as the sink config being used mandates flushes every second. There's no obvious sign of the sink worker failing to start in the logs, and of course this issue is not reproducible outside of CI
- changed the timeout to use require instead of assert so it subsequent tests wont run unless this precondition is met
- increased the maximum wait to 30s in lack of a better idea

Fail e2e tests for event ingest timeouts

---

.vscode/launch.json
cmd/jobs/config/loader.go
cmd/jobs/entitlement/init.go
cmd/jobs/entitlement/recalculatesnapshots.go
cmd/jobs/entitlement/root.go
cmd/jobs/main.go
cmd/jobs/service/otel.go
cmd/jobs/version.go
go.mod
go.sum
internal/entitlement/adapter/entitlement.go
internal/entitlement/balanceworker/recalculate.go
internal/entitlement/connector.go
internal/entitlement/repository.go
openmeter/entitlement/balanceworker/worker.go

This job can be used to trigger a recalculation of all the entitlement snapshots if needed.
The usage of cobra is because we will need additional jobs, such as the entitlement autoreset job, which we are planning to implement in openmeter using kubernetes cron jobs for now.

feat: add command to recalculate balance snapshots

---

pkg/clock/clock.go

Remove monotonic time reading from `time.Time` returned by `clock.Now()`.
This change help with comparing `time.Time` objects where one of them are generated by `clock.Now()` by forcing Go to use only the wall clock time for comparing them.

fix: strip monotonic clock reading from time returned by clock

---

go.mod
go.sum
internal/notification/webhook/events.go
internal/notification/webhook/secret.go
internal/notification/webhook/svix.go
internal/notification/webhook/webhook.go

Add `webhook` package with interface definistions and Svix implementation to `notification` package. This package will be used by Notification API to support sending events to user defined webhook endpoints.

feat: add webhook provider to Notification

---

internal/notification/repository.go
internal/notification/repository/repository.go
internal/notification/service.go

Add database transaction support to Notification API to properly handle failure scenarios.

feat: add tx support to Notification API

---

test/notification/testenv.go

Remove unnecessary check for empty environment variables as defaults are assigned if they are empty.

test: rm unnecessary envvar check

---

config.example.yaml
config/config_test.go
config/testdata/complete.yaml
internal/notification/webhook/svix.go
test/notification/testenv.go

Rename Svix API Key in configuration to make it backward compatible with other places where Svix is used/configured.

refactor: rename Svix API key in config

---

.github/workflows/artifacts.yaml

**Note:** this PR merges into the `depot-docker-build` branch.
This PR makes a few changes to the `artifacts.yaml` workflow to enable Trivy scanning of Docker images built with Depot. Buildx does not currently support the `oci` output when building using multiple "nodes" (servers), and Depot uses multiple build machines when building multi-platform images, to enable emulation-free builds for Arm.
Rather than downloading the final multi-platform image as an OCI tarball then, this PR instead saves the built image into the [Depot ephemeral registry](https://depot.dev/docs/guides/ephemeral-registry) using the `save: true` flag. Then the Trivy action is updated to scan that image directly by reference, using a temporary pull token.
As a bonus, this means that the `skopeo` workaround for the …

Use Depot ephemeral registry to run trivy scan

---

cmd/server/main.go
internal/notification/eventhandler.go
internal/notification/service.go

* fix notification configuration in router config
* return HTTP 404 for getting deleted rules
* fix event routing for webhook channels

fix: Notification API in backend

---

cmd/balance-worker/main.go
cmd/notification-service/main.go
config/balanceworker.go
config/config_test.go
config/events.go
config/notification.go
go.mod
internal/entitlement/balanceworker/worker.go
internal/notification/consumer/consumer.go
internal/watermill/driver/kafka/topic_provision.go
internal/watermill/router/context.go
internal/watermill/router/router.go
internal/watermill/router/router_test.go
openmeter/watermill/router/router.go

Given that most of our consumers implicitly depend on the ordering of the messages, this patch drops the retry queues and adds a simple DLQ solution.
The balance worker ignores any messages (e.g. ingest) coming after an entitlement deletion, but we are relying on the ordering there.
The notification worker relies on per-subject ordering so that it can check the database for previously sent alerts. Right now, out-of-order snapshots might trigger false notifications. (We can work around that.)
OSS-54

feat: simplify dlq setup

---

cmd/balance-worker/main.go
cmd/jobs/entitlement/init.go
cmd/notification-service/main.go
cmd/server/main.go
pkg/framework/entutils/database.go
pkg/framework/entutils/driver/driver.go
pkg/framework/pgdriver/driver.go
test/notification/helpers.go
test/notification/notification_test.go
test/notification/testenv.go

* split `ent` and `postgres/pgx` driver initialization into separate packages (`entutils/driver` and `pgdriver`)
* use `pgxpool` to have a better control over client connection pool to database
* allow instrumenting database client with custom tracing providers
* deprecate previously used `GetPGDriver` helper for backward compatibility

refactor: postgres/ent driver initialization

---

.github/workflows/ci.yaml
Makefile
atlas.hcl
ci/e2e.go
ci/migrate.go
dagger.json
flake.nix
tools/migrate/migrate.go
tools/migrate/migrate_test.go

1. Simple up-down-up on empty database (part of `go test ...`)
2. Validates that ent schema was generated (`internal/ent/db` in sync with `internal/ent/schema`)
3. Validates that migrations directory is in sync with schema (no diff)
4. Runs `atlas lint` for last 10 migration files checking for migrations being non-destructive and linear (10 is arbitrary)
5. Validates atlas checksum integrity (migration files weren't compromised)
The checks can also be run locally via `make migrate-check`
Note: it's templated locally, not the ideal solution but I have some skill issues with nix
- We should test that migrations work not just up-down-up but with a base of the latest release
The checks are implemented in dagger, and for dependency management a nix-in-dagger solution was used. This is somewhat …

Add CI checks in separate PR

---

internal/watermill/driver/kafka/subscriber.go

Given that we have retry and timeout middlewares in watermill we can set this to a high enough number.

feat: set max processing time for sarama consumers

---

cmd/balance-worker/main.go
cmd/notification-service/main.go
internal/entitlement/balanceworker/entitlementhandler.go
internal/entitlement/balanceworker/ingesthandler.go
internal/entitlement/balanceworker/worker.go
internal/watermill/eventbus/eventbus.go
internal/watermill/router/metrics.go
internal/watermill/router/router.go

This patch fixes the issue that a deleted event didn't cause the highwatermark cache to be update with isDeleted==true, due to the ordering of calls.
It also adds metrics and logging of errors for better understanding of how the handlers actually work.

fix: infinite loop processing events

---

internal/entitlement/entitlement.go
internal/notification/consumer/balancetreshold.go
internal/notification/consumer/consumer.go

As the entitlement's namespace is not part of the event.
Given we are only handling a specific type, I have only added a passthru method, later if there will be more event types we should accept cloudevents input.
As this is an internal entity it's fine to not to omit it from JSON tags.

fix: issues around balance snapshots

---

internal/notification/channel.go
internal/notification/repository/repository.go
internal/notification/rule.go
internal/notification/service.go
internal/notification/webhook/svix.go
internal/notification/webhook/webhook.go

Fix multiple issues in Notification API:
* webhook signing secret validation
* custom header not being set at notification channel creation
* balance threshold validation to allow >100% values for PERCENT type
* deleting notification channels assigned to active notification rules

fix: Notification API

---

internal/watermill/router/metrics.go
internal/watermill/router/router.go

The current metrics reporting reported error even if a handler failed, which might happen in case we receive the message faster than that data is committed to the database.
This patch ensures that we use warning level logging for handlers and detailed stats, but also we measure the whole e2e flow and only log DLQ events as errors.

feat: add support for dlq metrics

---

internal/notification/consumer/balancetreshold.go

The subject ID annotation was containing the payload instead of the actual subject ID.

fix: annotation should contain subject ID

---

cmd/jobs/entitlement/recalculatesnapshots.go
openmeter/entitlement/balanceworker/recalculate.go

We can use these metrics to determine the average time required to recalculate an entitlement in balance worker.
Fixes OM-877

feat: add recalculation metrics

---

cmd/jobs/entitlement/recalculatesnapshots.go
openmeter/entitlement/balanceworker/recalculate.go

This patch ensures that we can reuse the recalculator in multi-namespace scenarios.
This also allows us to allocate the meters only once.
Fixes #(issue)

refactor: allow recalculator reuse

---

openmeter/entitlement/balanceworker/recalculate.go
openmeter/entitlement/balanceworker/worker.go
openmeter/notification/consumer/consumer.go
openmeter/sink/flushhandler/handler.go
openmeter/sink/flushhandler/meters.go
openmeter/watermill/driver/kafka/broker.go
openmeter/watermill/grouphandler/grouphandler.go
openmeter/watermill/router/metrics.go

This patch improves the consistency/data available in consumer metrics. Changes:
- refactor: use int64 histograms (better for datadog, float64 ones are not working properly)
- refactor: add group handler metrics (So that we can report the skipped/ignored messages too.)
- refactor: unify router metrics (so that they are better aligned with the previous one)
- refactor: rename sarama metrics (Previously it was sarama.publisher.publisher / sarama.publisher.subscriber, now the redundant publisher part is dropped)
- refactor: use namespaces (e.g. watermill.router. for metrics, for easier debugging)

refactor: metrics

---

pkg/pagination/pagination.go

Add helpers to:
- Parse query params to `Page`
- Create `PagedResponse` from existing with transforming items type

feat(pagination): add helpers

---

openmeter/ent/db/migrate/schema.go
openmeter/ent/schema/entitlement.go
openmeter/entitlement/adapter/entitlement.go
openmeter/entitlement/metered/reset.go
openmeter/entitlement/repository.go
tools/migrate/migrations/20240903155435_entitlement-expired-index.down.sql
tools/migrate/migrations/20240903155435_entitlement-expired-index.up.sql
tools/migrate/migrations/atlas.sum

This patch allows getting the expired entitlements for all/multiple namespaces.
The added index helps with fetching expired entitlements for all namespaces.

feat: fetch expired entitlements for multiple namespaces

---

cmd/balance-worker/main.go
cmd/notification-service/main.go
cmd/server/main.go
go.mod
go.sum
pkg/framework/pgdriver/driver.go
pkg/pgxpoolobserver/observer.go

This patch exposes the connection pool statistics via opentelemetry, so that we see for all the workers the distribution of idle/acquired etc. connections.
Example metrics:
```
pgxpool_acquire_count_total{otel_scope_name="openmeter.io/backend",otel_scope_version=""} 4
pgxpool_acquire_duration_avg_milliseconds{otel_scope_name="openmeter.io/backend",otel_scope_version=""} 2
pgxpool_acquire_duration_milliseconds{otel_scope_name="openmeter.io/backend",otel_scope_version=""} 10
pgxpool_acquired_conns{otel_scope_name="openmeter.io/backend",otel_scope_version=""} 0
pgxpool_canceled_acquire_count_total{otel_scope_name="openmeter.io/backend",otel_scope_version=""} 0
pgxpool_constructing_conns{otel_scope_name="openmeter.io/backend",otel_scope_version=""} 0 …
```

feat: expose connection pool stats

---

config.example.yaml
config/config.go
config/config_test.go
config/helpers.go
config/kafka.go
config/sink.go
config/testdata/complete.yaml

Global Kafka configration (introduced in https://github.com/openmeterio/openmeter/pull/1475) would not work as certian services/components require a slightly different parameters to be set for the Kafka client initialized for them.
One solution would be to allow service/components to override certian parameters set in the global Kafka configuration, however it would introduce extra complexity around generating service specific KAfka configuration from multiple sources.
Another alternative to have dedicated Kafka configuration for all the service/components. It makes the configuration more verbose, but less complex/error prone.
This change implements the latter.

refactor: rm global Kafka configuration

---

config/kafka.go
config/sink.go

Make sure that all Kafka client config parameters are defaulted in order to make sure that Viper properly register/resolve them.

fix: Kafka config defaults

---

config/kafka.go

Fix default for broker address family configuration parameter.

fix: defaults for Kafka broker address family

---

quickstart/README.md

When multiple meters process the same event type, and one of them can't validate it, it'll be ignored by all meters. Consider using ClickHouse's `coalesce` in MVs: https://clickhouse.com/docs/en/sql-reference/aggregate-functions#null-processing

fix: quickstart

---

openmeter/watermill/driver/kafka/broker.go
openmeter/watermill/driver/kafka/metrics.go
openmeter/watermill/driver/kafka/metrics/adapter.go

This patch reduces (on the test environment) the number of metrics returned by sarama from 109 to 29.
Given that this is also linear to the number of brokers we have it should be more drastic in case of multi broker setups.
Example metrics:
```
sarama_incoming_byte_rate_for_broker_total{broker_id="1",otel_scope_name="openmeter.io/balance-worker",otel_scope_version="",role="publisher"} 69
sarama_incoming_byte_rate_for_broker_total{broker_id="1",otel_scope_name="openmeter.io/balance-worker",otel_scope_version="",role="subscriber"} 276925
```
Previously:
```
sarama_publisher_incoming_byte_rate_for_broker_1_total{otel_scope_name="openmeter.io/balance-worker",otel_scope_version=""} 300
```

fix: reduce the number of sarma metrics

---

pkg/slicesx/diff.go
pkg/slicesx/diff_test.go

Add a simple helper for calculating the difference between two slices.

feat: add diff util

---

openmeter/ent/db/migrate/schema.go
pkg/framework/entutils/mixins.go
tools/migrate/migrations/20240920070940_indexing-fixes.down.sql
tools/migrate/migrations/20240920070940_indexing-fixes.up.sql
tools/migrate/migrations/atlas.sum

This patch addresses two issues:
- The ID index must be unique (it's an ULID so there's an astronomically small chance for collusion)
- The ResourceMixin is a soft-delete resource, so the key must be unique for non-deleted items only.
For this migration we disable [MF101](https://atlasgo.io/lint/analyzers#MF101), which checks for adding a unique index to existing columns.

fix: mixin indexing tweaks

---

openmeter/ingest/kafkaingest/namespace.go
openmeter/watermill/driver/kafka/topic_provision.go
pkg/kafka/provisiontopic.go

Refactor helper used for provisioning Kafka topics to allow additional topic configuration.
Followeup PR will be created to consolidate implementations.

refactor: helper for provisioning Kafka topics

---

api/spec/src/notification/channel.tsp
api/spec/src/notification/event.tsp
api/spec/src/notification/rule.tsp
api/spec/src/notification/svix.tsp
api/spec/src/types.tsp

Add couple of fixes, improvments:
* re-add `visibility` to properties as it makes easier to reuse models for create/update operations
* fix update operation
* fix issue with friendlyName when templated
* fix formatting
* refactor using union of ULID and string for attributes where both area accepted

refactor(api): Notification API in TypeSepc

---

api/spec/src/entitlements/entitlements.tsp
api/spec/src/entitlements/grant.tsp
api/spec/src/notification/event.tsp
api/spec/src/notification/rule.tsp

Use `explode=true` for query parameters which accept multiple values in order to keep backward compatibility.

fix(api): query explode

---

api/api.gen.go
api/codegen.yaml
openmeter/customer/customer.go
openmeter/entitlement/driver/metered.go
openmeter/entitlement/driver/parser.go
openmeter/entitlement/snapshot/event.go
openmeter/notification/internal/rule.go
openmeter/productcatalog/driver/parser.go
test/notification/consumer_balance.go
test/notification/event.go

If the a field in OpenAPI spec is marked as readonly and required at the same time the Go code generator makes the field optional by setting its type to pointer which is not the desired behaviour.
Fortunatelly it is possible to disable this behaviour in the generator configuration.
See: https://github.com/oapi-codegen/oapi-codegen/issues/778

fix: required and readonly fields be optional

---

api/spec/src/cloud/main.tsp
api/spec/src/cloud/subjects.tsp
api/spec/src/entitlements/subjects.tsp
api/spec/src/events.tsp
api/spec/src/notification/rule.tsp
api/spec/src/portal.tsp

TypeSpec fixes after diffing with current OpenAPI

TypeSpec fixes

---

cmd/notification-service/main.go
cmd/server/main.go
config.example.yaml
config/config_test.go
config/notification.go
openmeter/notification/webhook/svix.go
openmeter/notification/webhook/webhook.go
test/notification/testenv.go
test/notification/webhook.go

* make timeout for event type register operation configurable (`notification.webhook.eventTypeRegisterTimeout`)
* allow skipping event type register in case the first attempt was unsuccessful in order to allow the service to start even in degraded state. (`notification.webhook.skipEventTypeRegisterOnError`)

refactor: mk webhook event type register non-critical

---

openmeter/streaming/clickhouse_connector/query.go
openmeter/streaming/clickhouse_connector/query_test.go

Alias meter table and prefix columns are used in the where condition to avoid shadowing by aggregated columns.
This fixes querying hourly and daily windows as well as filters the underlying per-minute windows, not the rounded tumbling window.

fix(streaming): alias meter query where

---

cmd/balance-worker/main.go
cmd/notification-service/main.go
cmd/server/main.go
cmd/sink-worker/main.go
config/aggregation.go
config/balanceworker.go
config/config.go
config/dedupe.go
config/events.go
config/ingest.go
config/kafka.go
config/namespace.go
config/notification.go
config/portal.go
config/postgres.go
config/sink.go
config/telemetry.go
openmeter/notification/webhook/svix.go
pkg/errorsx/errorsx.go
pkg/errorsx/errorsx_test.go

Instead of returning on error at a time, config now returns all validation errors.

Return all validation errors from configuration

---

openmeter/dedupe/redisdedupe/redisdedupe.go

The intention here should be to initialize a slice with a capacity of  `len(items)`  rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW

fix: fix slice init length

---

openmeter/server/router/event.go
pkg/errorsx/errorsx.go
pkg/errorsx/handler.go

Log list events validation errors on `warning` level. It is a temporary solution until we migrate the Events API to the new framework where logging and error handling are done differently.

refactor: log list events validation error on warn level

---

pkg/kafka/config.go

`max.poll.records` doesn't exist in Go client
https://github.com/confluentinc/confluent-kafka-go/issues/671

fix(sink): remove max poll records config

---

app/common/openmeter.go
cmd/server/wire_gen.go
openmeter/ingest/kafkaingest/collector.go

Use `TopicProvisioner` to ensure that the target topic for events is available on Kafka cluster in case Kafka driver is used for ingest. Provisioning results are caches i norder to avoid unnecessary roundtrips to between service and Kafka cluster.

feat(ingest): adopt topic provisioner

---

app/config/config_test.go
app/config/sink.go
app/config/testdata/complete.yaml
cmd/sink-worker/main.go
e2e/config.yaml
openmeter/ingest/kafkaingest/collector.go
openmeter/sink/sink.go
quickstart/config.yaml

* get namespace from event header instaed of the topic name it was received from
* refactor namespace, topic subscription logic by separating the two
* make topic name regexp configurable

refactor(sink): namespace and topic subscription update

---

app/common/telemetry.go
app/common/wire.go
cmd/balance-worker/main.go
cmd/balance-worker/wire.go
cmd/balance-worker/wire_gen.go
cmd/notification-service/main.go
cmd/notification-service/wire.go
cmd/notification-service/wire_gen.go
cmd/server/main.go
cmd/server/wire.go
cmd/server/wire_gen.go
cmd/sink-worker/main.go
cmd/sink-worker/wire.go
cmd/sink-worker/wire_gen.go

This PR simplifies how logging is initialized in the application to increase conformity with standards (OpenTelemetry in this case).
There is a cost however: if the application initialization fails, there is no logger to notify us about that failure (and it will never reach any OTLP exporter, since the "real" logger doesn't get initialized until the whole application initialization is done).
As a compromise, we initialize a basic JSON logger, since JSON is used in most production environments. If anything goes wrong during app init, that logger prints the error to `stderr`.
The recommended approach to deal with app init failures is to have additional monitoring in place that watches over running instances of an application. If there is a crash loop, you know something is up and can …

Drop separate logger initialization

---

openmeter/sink/sink.go

Make `no topics found to be subscribed to` logged on `warning` level.

fix(sink): no topic to subscibe warning

---

app/common/kafka.go
app/common/openmeter.go
app/config/config_test.go
app/config/ingest.go
app/config/testdata/complete.yaml
app/config/topicprovisioner.go
cmd/server/wire_gen.go
openmeter/ingest/kafkaingest/namespace.go
pkg/kafka/topicprovisioner.go
pkg/kafka/topicprovisioner_test.go

* allow defining list of topics which are protected from accidental deletion using TopicProvisioner.
* allowing namespace to be deleted by kafka namespace handler requires the `ingest.kafka.namespaceDeletionEnabled` configuration parameter explcitly set to `true`. It is set to `false` by default.

refactor(kafka): topic provisioning

---

app/common/watermill.go
app/config/events.go
cmd/jobs/entitlement/init.go
openmeter/testutils/logger.go
openmeter/watermill/eventbus/eventbus.go
pkg/kafka/topicprovisioner_test.go

This patch ensures that we are not getting circular dependencies due to the eventbus importing the config package.
A config helper is added to generate the required struct, but that should not cause any issues as this way the direction of the dependency is inversed.

refactor: fix circular dependency

---

README.md
docker-compose.yaml

feat(compose): add ch-ui

---

openmeter/billing/adapter.go
openmeter/billing/adapter/adapter.go
openmeter/billing/adapter/customeroverride.go
openmeter/billing/adapter/invoice.go
openmeter/billing/adapter/invoicelines.go
openmeter/billing/customeroverride.go
openmeter/billing/entity/invoice.go
openmeter/billing/errors.go
openmeter/billing/httpdriver/invoiceline.go
openmeter/billing/invoice.go
openmeter/billing/invoiceline.go
openmeter/billing/service.go
openmeter/billing/service/invoice.go
openmeter/billing/service/invoiceline.go
openmeter/billing/service/service.go
test/billing/invoice_test.go

This patch adds the required backend code for the create invoice now endpoint.
The overall logic is, that we take all of the pending invoice lines and whatever is due, we assign it to a new invoice. 
Further invoice changes will be handled by a proper state machine, but this transition requires cross-invoice state coordination.

feat: create invoice backend logic

---

openmeter/entitlement/balanceworker/recalculate.go

When an entitlement is not active anymore, the recalculator yields this error.
```
error sending event for entitlement [id=XXX]: failed to map entitlement value: unknown entitlement type
```

fix: treat inactive entitlement as deleted

---

app/common/telemetry.go
app/common/telemetry_test.go

The OTel slog bridge doesn't accept log-level configuration.

fix(telemetry): filter otel logs by log level

---

.dagger/generate.go
Makefile
api/client/go/client.gen.go
api/client/go/client.go
api/client/go/client_test.go
api/client/node/package.json
api/client/node/schemas/openapi.ts
api/openapi.cloud.yaml

- Generate clients after TypeSpec migration.
- Add tests to the Go client.
- Re-enable client gen for Node and Go clients

feat(client): go generate

---

app/common/telemetry.go
pkg/framework/pgdriver/driver.go

Upgrade semconv to 1.27.0 and migrate deployment name and URL path attributes.
This is a potential breaking change in monitoring and alerting if someone uses an observability tool that can't handle semconv upgrades gradually.

feat(otel): upgrade semconv to 1.27.0

---

cmd/server/main.go
cmd/sink-worker/main.go
openmeter/entitlement/repository.go
pkg/framework/operation/log.go

We use the default logger in multiple places, like NewServer, and extend it with more attributes, like route-level log context.
Without setting the app logger as default for slog this context is lost in Telemetry.

fix(log): contextual logging

---

cmd/server/main.go
openmeter/ingest/ingestdriver/http_transport_test.go
openmeter/server/server_test.go
pkg/errorsx/handler.go

- ContextHandler doesn't implement Handler interface
- NewAppHandler is always used with NewSlogHandler so filter logic is merged

refactor(framework): simplify logging handlers

---

.github/workflows/ci-exp.yaml
.github/workflows/ci.yaml
dagger.json
flake.lock

Bump Dagger to v0.14.0 and its dependencies to latest.

chore: bump Dagger to v0.14.0

---

openmeter/ingest/kafkaingest/serializer/json.go
openmeter/ingest/kafkaingest/serializer/serializer.go
openmeter/ingest/kafkaingest/serializer/serializer_test.go
openmeter/meter/validate.go
openmeter/meter/validate_test.go
openmeter/sink/namespaces.go

The Kafka event serializer always expected the data property to be set. This resulted in an incorrect 500 error for users.
This PR makes the data property optional and sets it as an empty string in the Kafka message.
This change need to be backported to the new parser: https://github.com/openmeterio/openmeter/pull/1720/files#diff-4b55946e836c7ec5383592308e9cde246b976ed16da8a83f571c413f46166252R75

fix(serializer): allow cloudevents without data

---

openmeter/productcatalog/plan/httpdriver/mapping.go

Return empty array instead of `null` for list of`PlanPhase` and `RateCards` to be aligned with the API spec.

fix(api): return empty array instead of null

---

docker-compose.yaml

Fix Postgres container logging `FATAL:  role "root" does not exist` by adjusting healthcheck in Docker Compose file.

fix: healthcheck for Postgres container

---

openmeter/ent/db/migrate/schema.go
openmeter/ent/schema/productcatalog.go
openmeter/productcatalog/plan/adapter/phase.go
openmeter/productcatalog/plan/adapter/plan.go
openmeter/productcatalog/plan/assert.go
openmeter/productcatalog/plan/service/phase.go
openmeter/productcatalog/plan/service/service_test.go
tools/migrate/migrations/20241119131528_plan.down.sql
tools/migrate/migrations/20241119131528_plan.up.sql
tools/migrate/migrations/atlas.sum

Fix updating RateCards in PlanPhase by using replace strategy in case in-place update is not possible. Like when the type of the RateCard is changed which is immutable attribute.

fix: updating RateCards in PlanPhase

---

openmeter/productcatalog/plan/adapter/plan.go
openmeter/productcatalog/plan/plan.go
openmeter/productcatalog/plan/service.go
openmeter/productcatalog/plan/service/plan.go
openmeter/productcatalog/plan/service/service_test.go

Ensure that only valid Plan can be promoted from `draft` to `active` by publishing.

fix: validate Plan before Publish

---

openmeter/productcatalog/plan/service/plan.go
openmeter/productcatalog/plan/service/service_test.go

Fix creating duplicated Plans due to insuifficient validation in Plan create operation.

fix: creating duplicated Plans

---

openmeter/app/sandbox/app.go
openmeter/app/sandbox/mock.go
openmeter/billing/adapter/invoice.go
openmeter/billing/adapter/invoicelinemapper.go
openmeter/billing/adapter/invoicelines.go
openmeter/billing/entity/app.go
openmeter/billing/entity/invoice.go
openmeter/billing/entity/invoiceline.go
openmeter/billing/entity/validationissue.go
openmeter/billing/service/invoice.go
openmeter/billing/service/invoicestate.go
openmeter/ent/db/billinginvoice.go
openmeter/ent/db/billinginvoice/billinginvoice.go
openmeter/ent/db/billinginvoice/where.go
openmeter/ent/db/billinginvoice_create.go
openmeter/ent/db/billinginvoice_update.go
openmeter/ent/db/billinginvoiceline.go
openmeter/ent/db/billinginvoiceline/billinginvoiceline.go
openmeter/ent/db/billinginvoiceline/where.go
openmeter/ent/db/billinginvoiceline_create.go
openmeter/ent/db/billinginvoiceline_update.go
openmeter/ent/db/migrate/schema.go
openmeter/ent/db/mutation.go
openmeter/ent/db/setorclear.go
openmeter/ent/schema/billing.go
test/billing/invoice_test.go
tools/migrate/migrations/20241207103019_billing-app-external-ids.down.sql
tools/migrate/migrations/20241207103019_billing-app-external-ids.up.sql
tools/migrate/migrations/atlas.sum

This patch adds support for invoicing apps, allowing to integrate with external parties such as Stripe.
The invoicing app is required to implement this interface or the invoicing flow will fail:
```
type InvoicingApp interface {
// ValidateInvoice validates if the app can run for the given invoice
ValidateInvoice(ctx context.Context, invoice Invoice) error
// UpsertInvoice upserts the invoice on the remote system, the invoice is read-only, the app should not modify it
// the recommended behavior is that the invoices FlattenLinesByID is used to get all lines, then the app should
// syncronize all the fee lines and store the external IDs in the result.
UpsertInvoice(ctx context.Context, invoice Invoice) (*UpsertInvoiceResult, error)
// FinalizeInvoice finalizes the invoice on the remote …
```

feat: invoicing app support

---

e2e/config.yaml
e2e/entitlement_test.go
openmeter/credit/balance.go
openmeter/credit/engine/engine.go
openmeter/credit/engine/engine_test.go
openmeter/credit/helper.go
openmeter/entitlement/metered/balance_test.go
openmeter/entitlement/metered/utils_test.go
openmeter/productcatalog/feature/connector.go
pkg/recurrence/period.go
pkg/recurrence/period_test.go

Implements balance calculation for meters with UNIQUE_COUNT aggregation.
Misc:
- Clean up `credit.engine` building logic
- Fix a bug that was codified in the tests 😮 (not user impacting)
We should really invest some time in setting up ClickHouse testing for non-e2e tests (maybe we could do use in-process instances, I'm not sure, but having to rely on E2E tests to cover anything ClickHouse specific is not great)

Unique count entitlements

---

openmeter/app/stripe/client/invoice.go
openmeter/app/stripe/entity/app/calculator.go
openmeter/app/stripe/entity/app/invoice.go
test/app/stripe/invoice_test.go

- Quantity is not supported without Stripe Billing.
- Add quantity to line item description
- Enable automatic tax collection by default

fix(invoice): stripe sync quantity

---

openmeter/billing/errors.go
openmeter/billing/service/profile.go
test/billing/profile_test.go
test/billing/suite.go

- Disallow deleting the default billing profile
- Make billing profile tests independent (not depending on previous test)

feat(billing): disallow deleting default profile

---

openmeter/subscription/testutils/compare.go

Adds missing assertions when comparing Specs and Views
Fixes [OM-1053: Test Validations](https://linear.app/openmeter/issue/OM-1053/test-validations)

Add missing assertions in Subscription tests

---

openmeter/billing/adapter.go
openmeter/billing/adapter/profile.go
openmeter/billing/customeroverride.go
openmeter/billing/httpdriver/profile.go
openmeter/billing/profile.go
openmeter/billing/service/profile.go
test/billing/profile_test.go

We must ensure that there is at least one default billing profile in the given namespace.
We achieve that by the following constraints:
Create:
- When creating a billing profile with default = true and a default billing profile exists then 
- the old billing profile set non-default, while the new billing profile is set to be the default
- When creating a billing profile with default = false, no checks are performed for the default profile
Update:
- When updating a non-default billing profile with default = true, the billing profile is made the default, 
- If there's an existing default billing profile it's default flag is set to false
- When updating a default billing profile with default = true, nothing changes
- When updating a default billing profile with default = false, the request …

fix: billing updated-at schemantics

---

openmeter/customer/adapter/customer.go
openmeter/customer/entity/errors.go
openmeter/customer/httpdriver/errors.go
openmeter/productcatalog/adapter/feature.go
openmeter/productcatalog/driver/errors.go
openmeter/productcatalog/feature/feature.go
openmeter/productcatalog/subscription/service/change_test.go
openmeter/productcatalog/subscription/service/migrate_test.go
openmeter/subscription/repo/subscriptionrepo.go
openmeter/subscription/repo/utils.go
openmeter/subscription/service/service_test.go
openmeter/subscription/service/update_test.go
openmeter/subscription/service/workflowservice_test.go
openmeter/subscription/testutils/customer.go
openmeter/subscription/testutils/db.go
openmeter/subscription/testutils/repository.go
openmeter/subscription/testutils/service.go
test/customer/customer.go
test/customer/customer_test.go
test/customer/testenv.go

- Disallow updating custom UsageAttribution if a Subscription is present
- Disallow archiving features used in active or scheduled plans or subscriptions
- Due to how features are currently linked in plans & subscriptions, logically speaking a feature can rarely be archived once its used in the productcatalog/subscription subsystem. I added a ticket to clean this up at a later point (might even make sense to do away with "archiving" for features)

Add checks for Subscription dependencies so they cannot be updated inconsistently

---

openmeter/subscription/events.go
openmeter/subscription/service/service.go

This patch fixes that subscription have published the wrong events on some action.
Fixes that Update didn't yield an event.
Adds the deleted event type.

fix: correct subscription event publishing

---

app/common/billing.go
app/common/subscription.go
cmd/server/wire_gen.go
openmeter/billing/subscription/validator.go
openmeter/productcatalog/subscription/http/errors.go
openmeter/subscription/service/service.go
openmeter/subscription/subscriptionvalidator.go

This patch makes sure that if we are starting a subscription that would yield an invoice, then we could most probably create the invoice.
This feature ensures that we don't end up with draft_failed invoices in trivial cases.

feat: add validate billing stack before creating a paid subscription

---

openmeter/productcatalog/discount.go
openmeter/productcatalog/entitlement.go
openmeter/productcatalog/errors.go
openmeter/productcatalog/phase.go
openmeter/productcatalog/plan.go
openmeter/productcatalog/plan/adapter/plan.go
openmeter/productcatalog/plan/errors.go
openmeter/productcatalog/plan/errors_test.go
openmeter/productcatalog/plan/httpdriver/errors.go
openmeter/productcatalog/plan/phase.go
openmeter/productcatalog/plan/plan.go
openmeter/productcatalog/plan/ratecard.go
openmeter/productcatalog/price.go
openmeter/productcatalog/ratecard.go
openmeter/productcatalog/subscription/http/errors.go
openmeter/productcatalog/subscription/service/plan.go
openmeter/productcatalog/subscription/testutils/adapter.go
openmeter/productcatalog/tax.go
openmeter/productcatalog/tax_test.go

* use `ValidationError` to wrap validation errors
* rework Plan `NotFoundError` to capture additional metadata

refactor: productcatalog errors

---

atlas.hcl
docs/migration.md
openmeter/testutils/pg_driver.go
tools/migrate/migrate_test.go
tools/migrate/productcatalog_test.go

Adds some simple tooling in `tools/migrate` so that during our migration test we can stop at specific versions and make modifications & assertions on the database state. This enables testing what happens to already present data after a migration. An example for the `start_after` => `duration` migration is added to demonstrate the concept and the recommended structure of adding such tests.

Testing data-migrations

---

app/config/config_test.go
app/config/events.go
openmeter/watermill/router/logger.go
openmeter/watermill/router/router.go

This patch ensures that the max retires is set, if we have a retry timeout, as without the max retries watermill would never retry.
Given that in our use-case we also have DLQ, that would print an error if a final issue happens, we decrease the severity of a retry message to warning.

fix: watermill retry logic and error reporting

---

openmeter/entitlement/entitlement.go
openmeter/entitlement/scheduling.go
openmeter/productcatalog/phase.go
openmeter/productcatalog/ratecard.go

Disallow creating Plans & Entitlements with durations less than 1 hour
- The PlanPhase & RateCard validation is the same between create & otherwise assertion. Due to this if there were previous phases shorter than 1h those would always error afterwards. In our environments there **aren no** such entries.

feat: disallow durations less than an hour

---

openmeter/entitlement/boolean/connector.go
openmeter/entitlement/metered/connector.go
openmeter/entitlement/static/connector.go
openmeter/subscription/testutils/compare.go

Due to missing mappings Subscription Managed entitlements could be deleted which bricked the entire subscription afterwards.
To heal any broken entitlements in the DB this query can be run (there are non in our environments right now)
```sql
UPDATE entitlements 
SET subscription_managed = true 
FROM (
SELECT entitlement_id FROM subscription_items WHERE entitlement_id IS NOT NULL
) AS items 
WHERE items.entitlement_id = entitlements.id;
```

Fix Subscription Managed Entitlements

---

openmeter/app/stripe/client/client.go

Set Stripe webhook api version to avoid:
```
failed to construct webhook event: Received event with API version 2023-10-16, but stripe-go 80.2.1 expects API version 2024-09-30.acacia. We recommend that you create a WebhookEndpoint with this API version. Otherwise, you can disable this error by using `ConstructEventWithOptions(..., ConstructEventOptions{..., ignoreAPIVersionMismatch: true})`  but be wary that objects may be incorrectly deserialized.
```

fix(stripe): set webhook api version

---

e2e/entitlement_test.go

Increases assertion timeout from 1 min to 2 as theoretically it was possible that not all events fell in the current minute period.
The above theoretical doesn't explain the real life experience that when the test fails no events are registered.

fix(e2e): increase timeout

---

dagger.json

Remove unused `nix` module from Dagger dependencies.

ci: rm unused Nix module

---

flake.nix
go.mod
go.sum

Bump confluent-kafka-go to v.2.8.0.
https://github.com/confluentinc/confluent-kafka-go/releases/tag/v2.8.0

chore: bump confluent-kafka-go to v.2.8.0

---

openmeter/productcatalog/plan.go
openmeter/productcatalog/plan/service/plan.go

Fix validations errors by wrapping them with `productcatalog.ValidationError` in order return HTTP 400 response instead of HTTP 500.

fix: wrapping validation errors properly

---

app/common/billing.go
app/common/openmeter_billingworker.go
app/common/openmeter_server.go
cmd/billing-worker/wire_gen.go
cmd/jobs/billing/advance/advance.go
cmd/server/wire_gen.go
openmeter/app/entity/base/app.go
openmeter/billing/adapter/validationissue.go
openmeter/billing/events.go
openmeter/billing/profile.go
openmeter/billing/service/invoice.go
openmeter/billing/service/invoiceline.go
openmeter/billing/service/service.go
openmeter/billing/worker/subscription/sync.go
openmeter/billing/worker/subscription/sync_test.go
openmeter/billing/worker/worker.go
openmeter/customer/entity/customer.go
openmeter/event/metadata/resourcepath.go
test/billing/suite.go

The subscription -> billing sync is designed in a way, that we are feeding the billing with new lines when needed. There are two conditions that would necessitate such a synchronization:
- Something changes in a subscription (it's already implemented)
- We bill our customers (as then the gathering invoice's items are removed/consumed, so we need to backfill it)
For this we are relying on the eventbus.
```json
{
"id": "01JHTC8JNMKD60E3NVTSQ7KFJ1",
"source": "//openmeter.io/namespace/default/invoice/01JHTC8JMWTD0BEWYBA1SCSSZP",
"type": "io.openmeter.billing.v1.invoice.created",
"subject": "//openmeter.io/namespace/default/customer/01JHTC8C2S00P0HF8730DPWEKF",
"datacontenttype": "application/json",
"time": "2025-01-17T14:56:48.820492Z",
"data": {
"namespace": "default", …
```

feat: implement subscription line adding on invoice creation

---

openmeter/entitlement/adapter/entitlement.go
openmeter/subscription/repo/subscriptionphaserepo.go
openmeter/subscription/service/sync.go
openmeter/subscription/service/workflowservice_test.go
openmeter/subscription/testutils/service.go
openmeter/testutils/time.go
test/subscription/framework_test.go
test/subscription/scenario_editcancel_test.go

Adds more tests for Subscription Edit, and gets rid of redundant code-paths from sync logic
- The reason the sync codepath were redundant is because a change in the relevant entitlement would also constitute a change in the SubscriptionItem, so the logic just above would handle all cases

Add more Tests for Subscription Edit

---

openmeter/billing/service/invoice.go

Right now we have a sugar on gathering invoices that calculates the totals, for that we fetch all the lines regardless of the expand settings.
This patch ensures that we are emulating the expand settings in terms of lines so that we are not returning extra data.

fix: split lines should not be returned for gathering invoices

---

openmeter/billing/service/invoice.go
openmeter/billing/service/invoicestate.go

This patch makes sure that the invoice action is properly set for invoices where the list of lines are available.

fix: invoice action on gathering invoices

---

openmeter/productcatalog/subscription/http/get.go
openmeter/subscription/subscriptionview.go

- For other phases all items will be inactive so it makes sense to return the top "status"
- History is already hidden for all Items

Hide inactive Items from current Phase of Subscription response

---

collector/quickstart/collector/config.yaml
collector/quickstart/collector/resources/dedupe-cache.yaml
collector/quickstart/collector/streams/input.yaml
collector/quickstart/collector/streams/output.yaml
collector/quickstart/docker-compose.yaml
collector/quickstart/seeder/config.yaml
quickstart/config.yaml
quickstart/docker-compose.yaml

Add an example for deploying Collector with Openmeter to Quickstart.

feat: add collector to quickstart

---

openmeter/app/stripe/client/appclient.go
openmeter/app/stripe/client/client.go
openmeter/app/stripe/client/invoice.go
openmeter/app/stripe/entity/app/invoice.go
openmeter/app/stripe/httpdriver/webhook.go
openmeter/billing/app.go
openmeter/billing/service/invoicestate.go
test/app/stripe/invoice_test.go

- Do not set invoice statement descriptor at Stripe sync
- Do not set invoice number at Stripe sync
- Save Stripe Stripe-generated invoice number at the update
- Subscribe to invoice payment related Stripe events (no-ops for now)
- Subscribe to payment intent failure events (no-ops for now)

feat(stripe): subscribe to invoice webhooks

---

openmeter/billing/worker/subscription/sync.go
openmeter/billing/worker/subscription/sync_test.go

This allows us to properly maintain the updatedAt of the invoice base, and decreases the amount of invoice update events.
The patch only fixes the sync, as capturing this in the adapter is a more complex venture, also except of gathering invoices, if we edit an invoice there will be an update due to the status change either ways.

feat: only syncronize lines that have changed

---

openmeter/app/stripe/adapter/customer.go
openmeter/app/stripe/adapter/stripe.go
openmeter/app/stripe/client/appclient.go
openmeter/app/stripe/client/stripe.go
test/app/stripe/appstripe.go
test/app/stripe/fixture.go
test/app/stripe/invoice_test.go
test/app/stripe/testenv.go

Validate if the Stripe app customer and payment method exist before saving it.

feat(app): stripe app validate customer data

---

openmeter/app/stripe/client/appclient.go
openmeter/app/stripe/client/invoice_line.go
openmeter/app/stripe/entity/app/invoice.go
openmeter/billing/adapter/invoice.go
openmeter/billing/service/invoice.go
openmeter/billing/worker/subscription/sync_test.go
test/app/stripe/invoice_test.go
test/app/stripe/stripe_mock.go
test/billing/invoice_test.go

This patch fixes the issues found around executing the flowing scenario:
- Have a draft invoice backed by stripe app
- Replace a line in the draft invoice by another line
- Sync fails
Fixes included:
- Make sure we are assigning the new line's IDs during state machine transitions by calling the updateInvoice
- Make sure that we are always expanding the Invoice object with the service parts by using the service.updateInvoice call
- Make sure that we are always saving the invoice line stripe ID to external ID instead of the invoice item ID
- Support lookups in sync code by invoice item ID as a fallback
- [misc] Do not double-call status details calculations

fix: stripe sync issues

---

openmeter/billing/events.go
openmeter/billing/worker/subscription/sync.go
openmeter/billing/worker/worker.go

We need to remove the invoice.Workflow.Apps member as it's not json serializable.
Either ways, the apps service should be used in workers to acquire an up-to-date app based on the payload.Workflow.AppReferences

fix: invoice event unmarshaling

---

app/common/billing.go
cmd/jobs/billing/billing.go
cmd/jobs/billing/collect/collect.go
cmd/jobs/internal/wire.go
cmd/jobs/internal/wire_gen.go
openmeter/billing/service/collectionat.go
openmeter/billing/service/invoice.go
openmeter/billing/worker/collect/collect.go

Implement invoice collector worker and job.

feat(billing): implement invoice collector

---

app/common/billing.go
cmd/billing-worker/wire_gen.go
cmd/jobs/internal/wire_gen.go
cmd/server/wire_gen.go

The stripe app service is not required by billing, as it accesses it using the app's registry.
The stripe app will need to access billing to trigger actions based on the webhooks, thus we are eliminating a circular dependency.

fix: billing dependency cleanup

---

openmeter/productcatalog/plan/service/plan.go

Remove unnecessary pagination when listing existing Plans to find the version number for the next draft plan.

refactor: rm unnecessary pagination

---

.dagger/generate.go
.dagger/release.go
.dagger/versions.go

Install latest `corepack` in dagger tagets to fix `Error: Cannot find matching keyid` errors.

fix: corepack pkg manager install

---

.dagger/migrate.go
.dagger/versions.go
.dagger/versions_pinned.go
flake.nix

Bump `atlas` version to v0.30.0.

chore: bump atlas to v0.30.0

---

.vscode/launch.json
app/common/billing.go
app/common/config.go
app/config/billing.go
app/config/config.go
app/config/config_test.go
cmd/billing-worker/wire_gen.go
cmd/jobs/internal/wire_gen.go
cmd/server/wire_gen.go
config.example.yaml
openmeter/billing/events.go
openmeter/billing/service.go
openmeter/billing/service/invoice.go
openmeter/billing/service/service.go
openmeter/billing/serviceconfig.go
openmeter/billing/worker/asyncadvance/asyncadvance.go
openmeter/billing/worker/worker.go
test/app/testenv.go
test/billing/suite.go

This patch allows for invoices to be processed by the billing-worker instead of being processed by the server during the HTTP call.
For apps that are slower to process it's a better user experience, while it gives us more space to execute the synchronization steps.

feat: add support for background invoice progressing

---

openmeter/productcatalog/plan.go

Fix publishing Plan with Phases having no RateCards by validating Plan at publish request and returning validation error if there are Phases without RateCards.

fix: empty Plan Phase validation

---

openmeter/billing/adapter/invoice.go
openmeter/billing/httpdriver/invoice.go
openmeter/billing/invoice.go
openmeter/billing/service/invoice.go
openmeter/billing/service/invoicestate.go
openmeter/ent/db/billinginvoice.go
openmeter/ent/db/billinginvoice/billinginvoice.go
openmeter/ent/db/billinginvoice/where.go
openmeter/ent/db/billinginvoice_create.go
openmeter/ent/db/billinginvoice_update.go
openmeter/ent/db/migrate/schema.go
openmeter/ent/db/mutation.go
openmeter/ent/db/runtime.go
openmeter/ent/db/setorclear.go
openmeter/ent/schema/billing.go
test/billing/invoice_test.go
tools/migrate/migrations/20250207101313_billing-store-status-details.down.sql
tools/migrate/migrations/20250207101313_billing-store-status-details.up.sql
tools/migrate/migrations/atlas.sum

This allows for checking the DB for stuck invoices that would otherwise need to fetch data from state machine.
As a sideeffect we are also reducing the load on the DB due to some locks being unnecessary with this setup.

feat: store status details in DB

---

openmeter/sink/flushhandler/handler.go
openmeter/sink/flushhandler/mux.go
openmeter/sink/flushhandler/types.go
openmeter/sink/sink.go

Fix deadlock during draining events channel in flushhadler. This should fix the `failed to shutdown flush success handlers` error messages reported by `sink-worker` during shutdown.

fix(sink): deadlock in flushhandler

---

go.mod
go.sum

Bump `github.com/oklog/run` to `v1.1.1-0.20240127200640-eee6e044b77c`.

chore(deps): bump github.com/oklog/run to v1.1.1-0.20240127200640-eee6e044b77c

---

flake.lock

Make lint fails to work with the old version.

chore: update dagger to v0.15.3

---

cmd/balance-worker/main.go
cmd/benthos-collector/main.go
cmd/billing-worker/main.go
cmd/jobs/main.go
cmd/notification-service/main.go
cmd/server/main.go
cmd/sink-worker/main.go
pkg/paniclogger/paniclogger.go

This patch makes sure that panics are logged with stack trace information if not caught by the components handler.

feat: log panics with stack trace

---

app/common/watermill.go
cmd/balance-worker/wire_gen.go
cmd/billing-worker/wire_gen.go
cmd/jobs/internal/wire_gen.go
cmd/notification-service/wire_gen.go
cmd/server/wire_gen.go
cmd/sink-worker/wire_gen.go
openmeter/watermill/driver/kafka/broker.go

Fix `sarama` logging configuration by always setting `sarama.DebugLogger` in order to avoid redeirecting debug log to `sarama.Logger` logger which is the default behaviour if the former is not set.
See: https://github.com/IBM/sarama/blob/main/sarama.go#L135-L139

fix: sarama debug log

---

openmeter/streaming/clickhouse/materialized_view/meter_query.go
openmeter/streaming/clickhouse/raw_events/meter_query.go
openmeter/streaming/clickhouse/raw_events/meter_query_test.go

We don't need to check for value prop. Checking for value prop can cause issues with incorrectly created meters.

fix(streaming): aggregation condition for count

---

app/common/config.go
app/common/termination.go
app/config/config.go
app/config/config_test.go
app/config/telemetry.go
app/config/termination.go
app/config/testdata/complete.yaml
cmd/server/.air.toml
cmd/server/main.go
cmd/server/wire.go
cmd/server/wire_gen.go
config.example.yaml
go.mod
go.sum
openmeter/ingest/kafkaingest/collector.go
pkg/gosundheit/logger.go

* fix stopping service/actors in reverse order on process termination by reordering actors and using forked version of `oklog/run` (until upstream accepts PR or introduces similar feature)
* fix updating readiness endpoint on process termination by intorducing `TerminationChecker` which is registered in healthchecker and also added as an actor to control (deplay) process termination

fix: shutdown procedure in server

---

collector/benthos/bloblang/parse_resource.go
collector/benthos/input/run_ai.go
collector/benthos/input/runai/metrics.go
collector/benthos/input/runai/service.go
collector/benthos/input/runai/token.go
collector/benthos/input/runai/workloads.go
go.mod
go.sum

Example config:
```yaml
logger:
level: DEBUG
input:
run_ai:
url: "${RUNAI_URL:}"
app_id: "${RUNAI_APP_ID:}"
app_secret: "${RUNAI_APP_SECRET:}"
schedule: "${RUNAI_SCRAPE_SCHEDULE:*/30 * * * * *}"
metrics:
- CPU_LIMIT_CORES
- CPU_MEMORY_LIMIT_BYTES
- CPU_MEMORY_REQUEST_BYTES
- CPU_MEMORY_USAGE_BYTES
- CPU_REQUEST_CORES
- CPU_USAGE_CORES
- GPU_ALLOCATION
- GPU_MEMORY_REQUEST_BYTES
- GPU_MEMORY_USAGE_BYTES
- RUNNING_POD_COUNT
http:
timeout: "30s"
retry_count: 1
retry_wait_time: "100ms"
retry_max_wait_time: "1s"
pipeline:
processors:
- mapping: |
let duration_seconds = (meta("scrape_interval").parse_duration() / 1000 / 1000 / 1000).round().int64()
root = {
"id": "%s-%d-%s".format(this.metrics.timestamp, $duration_seconds, this.id).hash("sha1").encode("hex"),
"type": …
```

feat(collector): run-ai collector

---

openmeter/entitlement/driver/parser.go

Fix interval parsing/mapping by converting interval string to upper case so patternmetching won't fail on case mismatch.
Example error:
```
failed to map interval: year: expected 'P' period mark at the start
```
We might want to add validation to OAPI spec as well.

fix: interval parsing

---

Dockerfile
benthos-collector.Dockerfile
entrypoint.sh

Add `entrypoint.sh` script to Docker images in order to allow injecting CA Root certificates at runtime by mounting the certificates to `/usr/local/share/ca-certificates` directory in the container.
The `entrypoint.sh` script checks if `/usr/local/share/ca-certificates` has files in it and runs the `update-ca-certificates` script at contianer start up.

feat: add entrypoint script

---

app/common/kafka.go

Disable collecting statistics in Kafka admin client as the data is colelcted in an internal queue which needs to be consumed but the AdminClient does not provide interface for that (one possible solution would be to derive AdminClient from Producer and run poll() in background, but we do not really need stas for admin clietns) in order to avoid growing memory.

fix: disable stats for Kafka admin client

---

.dagger/test_e2e.go
.gitignore
app/config/telemetry.go
config.example.yaml
e2e/config.yaml

The E2E tests difficult to debug as the service logs are surpassed by dagger. This PR adds simple file-logging to openmeter and enables it for the E2E tests. **If the E2E tests all logs are printed at the end.**
- It would be better if the logs could be saved to a file that can be parsed separately, we should eventually add that as an incremental upgrade, but I couldn't make that work in reasonable time.
- Sharing the log volume between dagger containers & services uses cache mounts. There's no concept of a shared mounted directory otherwise. This pollutes the number of caches we use, but in theory that shouldn't be a problem.
- Both sink and the api logs to the same file
```
Error logs:
✘ .withExec(args: ["sh", "-c", ETOOBIG:sha256:f7b927067baf994023e36cec34ac0b8fce2e6e61c73dfee1706dde8ac …
```

Expose logs of E2E tests

---

openmeter/customer/httpdriver/errors.go
openmeter/entitlement/driver/errors.go

Fixes 500 errors with:
```failed to query meter: validate params: validation error: from must be rounded to MINUTE like YYYY-MM-DDTHH:mm:00```
On any entitlements querying endpoint.
Fixes #(issue)

chore: fix 500 on meter validation errors

---

openmeter/entitlement/metered/balance.go
openmeter/entitlement/metered/balance_test.go
openmeter/meter/meter.go
openmeter/streaming/testutils/streaming.go
openmeter/streaming/testutils/streaming_test.go

The clickhouse mock-connector incorrectly implemented aggregation which threw off the tests building on it. Now the behavior of what rows are returned when windowing matches what ClickHouse does.
- Return all history windows (even if no usage events were recorded)
- Check that we only return windows in which the entitlement existed for the whole period

Fix History Windowing

---

openmeter/entitlement/balanceworker/ingesthandler.go
openmeter/sink/flushhandler/ingestnotification/events/events.go
openmeter/sink/flushhandler/ingestnotification/handler.go
openmeter/subscription/validators/customer/validator.go

Previously we were using random partitions for ingest events, making the high watermark cache unusable. This patch ensures that we are consistent with partition selection.

chore: fix ingest event partition assignment

---

openmeter/billing/service/invoice.go
openmeter/billing/service/invoiceline.go
openmeter/billing/service/lineservice/linebase.go

So that we can have more efficient caching of features meters going forward.

refactor: rely on FromEntities where it makes sense

---

flake.lock

chore: nix update devenv

---

openmeter/productcatalog/plan/adapter/plan.go

If effectiveTo < effectiveFrom the plan is considered invalid.
This should not happen, as we have validations in place, but let's correct the check.

fix: plan listing invalid filter

---

openmeter/customer/adapter/customer.go
openmeter/subscription/service/service.go

On the long run we should have a specific method that updates the currency, as on the next field in customer we will have the same issue.

fix: do not reset key on subscription starting

---

openmeter/subscription/service/sync.go
openmeter/subscription/service/synchelpers.go
openmeter/subscription/subscriptionspec.go
test/subscription/scenario_editaligned_test.go

Entitlement usage period will be same as aligned billingperiod for the subscription if the subscription is aligned (derived from the current phase start)

Fix entitlement alignment on aligned edits

---

openmeter/billing/service/invoice.go
openmeter/billing/worker/subscription/sync.go

Fixes the issue when there's a subscription is canceled at the end of the billing period and there was no sync.
This fixes the following error:
```
failed to reconcile subscription [namespace=org_2l3uuzkgTdvCyom82y11jeZO2u5 subscriptionID=01JFQR5CWX8DJYPFKACQ5GB6CC]: updating mutable invoice[01JKBTW7YF0E9V7Y0PDZWM5A0A]: deleting empty invoice: cannot trigger_delete invoice in status [gathering]: invoice action not available
```

fix: gathering invoice deletion from sync

---

openmeter/subscription/service/errors.go
openmeter/subscription/service/workflowservice.go

Let's use a unified errorMapper to map package internal errors to public errors

Map subscription errors in workflow service

---

openmeter/app/stripe/entity/app/invoice.go

The invoice has already snapshotted the workflow value, let's use that instead of fetching a maybe diverging one.

fix: use invoice's workflow settings

---

openmeter/productcatalog/planaddon/httpdriver/mapping.go

Fix missing `maxQuantity` from HTTP API request mapper.

fix: maxQuantity in API request mapper 

---

openmeter/streaming/clickhouse/cache.go
openmeter/streaming/clickhouse/cache_test.go
openmeter/streaming/clickhouse/connector.go

This PR queries the non-cached and fresh period in one go, reducing the number of queries.
Queries before:
1. Get rows for the cachable period
2. Get non-cached rows
3. Get rows for non cachable period (fresh)
Queries after:
1. Get rows for the cachable period
2. Get rows since the last cached to the original query to

refactor(cache): query non-cache and fresh period in one go

---

openmeter/customer/service/hooks/subject.go
openmeter/customer/service/hooks/subject_test.go

Skip migrating Stripe customer id for customer which has a payment app setup in their billing profile with type other than Stripe.

refactor: ignore/log payment app type mismatch

---

openmeter/billing/worker/subscription/sync.go

This patch makes sure that the period correction logic:
- Is only executed for lines where the transition happens
- The checks are relaxed, so that we only mandate service period and  full service period start to match
- If billing periods matching the service period, let's update the billing   period too, so that invoiceAt gets updated properly.

fix: invalid error on period correction

---

openmeter/entitlement/balanceworker/entitlementhandler.go
openmeter/watermill/router/errors.go
openmeter/watermill/router/metrics.go

This patch logs the entitlement not found errors as warnings, given that rolled back transactions also fire events.
Due to this we can expect that sometimes the entitlement is not found.
We still need to retry, as if the originating transaction is running for a while, the entitlement might appear after the transaction is committed.

chore: reduce worker noise
